//! FFI bindings for the Apple frontend.
//!
//! The Apple shell (`apple/Dub`) links against this crate via the
//! `DubCore.xcframework` that [`scripts/build-xcframework.sh`] produces.
//! Swift bindings are generated by UniFFI in library mode — there is no
//! hand-written `.udl` file; the `#[uniffi::export]` proc macros on
//! Rust items below are the single source of truth.
//!
//! ## Surface
//!
//! * Two free functions for the M0.5 smoke screen: [`greeting`] and
//!   [`engine_version`]. Used by `SmokeScreenView` in the Apple shell.
//! * [`DubEngine`] (M10-A): a stateful handle the Apple shell holds
//!   for the lifetime of a "Thru session". Exposes
//!   - `list_input_devices` (read-only)
//!   - `start_thru` / `stop_thru` (lifecycle)
//!   - `peaks_extend` / `peaks_len` / `peaks_chunk_duration_secs`
//!     (broadband waveform data)
//!   - `band_peaks_extend` / `band_peaks_len` /
//!     `band_peaks_chunk_duration_secs` (M9.5b-shipped 8-band
//!     loudness data — used by the M10.1 multi-colour shader)
//!
//! ## Stability contract
//!
//! All errors are surfaced via [`EngineError`]; no panics ever cross
//! the FFI boundary (`.cursor/rules/ffi.mdc`). All `peaks_*` methods
//! return defensive zero / empty values when the named deck has no
//! capture stream, so the Swift renderer never panics on a stale
//! `start_idx`.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

use std::sync::{Arc, Mutex};

use dub_audio::{AudioInput, AudioOutput, InputOptions, OutputOptions};
use dub_engine::{Engine, EngineHandle, ThruInputConfig, INTERNAL_MIXER_ROUTING};
use dub_io::Track;
use dub_peaks::{
    compute_offline_peaks, BandPeakChunk, OfflinePeaks, PeakChunk, PeakStream, PeakStreamConfig,
};

// UniFFI scaffolding. Emits the C ABI symbols (component contract,
// metadata symbol, RustBuffer alloc/free) that the generated Swift
// bindings depend on. Must be called exactly once per UniFFI-exporting
// crate.
uniffi::setup_scaffolding!();

/// FFI surface version. Bump when adding or removing exported symbols.
///
/// Not currently exposed via UniFFI — Swift consumers verify ABI
/// compatibility through the bindings file UniFFI generates, which
/// embeds a content-hashed checksum per exported function. This
/// constant is kept as a *Rust-side* tripwire so workspace integration
/// tests can fail loudly if someone bumps the surface without updating
/// the version.
///
/// `3`: M10.1 added [`DubEngine::sample_rate`].
/// `4`: M10.2 added [`DubEngine::start_thru_two_deck`] for deck B
///      wiring.
/// `5`: M10.5 added File-mode playback: `start_engine` (output-only
///      lifecycle), `load_track`, `play`, `pause`, `seek`, `position`,
///      `track_info`. `peaks_extend` / `peaks_len` / etc. now read
///      from either the Thru analysis thread or the offline-decoded
///      peak buffer transparently via the per-deck `PeakSource` enum.
pub const FFI_VERSION: u32 = 5;

/// Returns a static greeting string. The Apple shell calls this on launch
/// to verify it linked the Rust core successfully.
#[uniffi::export]
pub fn greeting() -> String {
    String::from("Dub engine OK")
}

/// Returns the version of the underlying `dub-engine` crate (the
/// `CARGO_PKG_VERSION` baked in at compile time).
#[uniffi::export]
pub fn engine_version() -> String {
    String::from(dub_engine::VERSION)
}

/// Maximum Thru block size, in frames. Mirrors `dub-cli`'s
/// `THRU_MAX_BLOCK_FRAMES` — CoreAudio variable buffers can reach
/// ~4096 frames per IOProc on certain devices, and `ThruSource`'s
/// debug assertion enforces this ceiling so a bigger callback would
/// panic on attach. Sized 1 KiB above CoreAudio's known worst case so
/// any future driver expansion doesn't tip us over silently.
const THRU_MAX_BLOCK_FRAMES: usize = 5120;

/// Engine block size in frames, used when constructing the audio
/// graph. 256 matches the `dub-cli` default and gives a good balance
/// between latency (5.3 ms at 48 kHz) and scheduling overhead.
const ENGINE_BLOCK_FRAMES: usize = 256;

/// Errors surfaced across the UniFFI boundary.
///
/// `flat_error` because most variants don't carry structured data
/// the Swift side needs to branch on — a string is the most
/// ergonomic interop format. The few variants that *do* carry data
/// (e.g. `DeviceNotFound`) embed it into the `Display` impl.
#[derive(Debug, thiserror::Error, uniffi::Error)]
#[uniffi(flat_error)]
#[allow(missing_docs)]
pub enum EngineError {
    #[error("device not found: {0}")]
    DeviceNotFound(String),

    #[error("invalid channels: {0:?}")]
    InvalidChannels(Vec<u32>),

    #[error("audio start failed: {0}")]
    AudioStartFailed(String),

    #[error("engine is already running; call stop_thru first")]
    AlreadyRunning,

    #[error("engine is not running")]
    NotRunning,

    #[error("invalid deck index {0} (valid: 0..{count})", count = dub_engine::DECK_COUNT)]
    InvalidDeckIndex(u64),

    /// File decoding failed (unsupported codec, corrupt file, IO error,
    /// or unsupported channel layout). M10.5.
    #[error("track decode failed: {0}")]
    TrackDecodeFailed(String),

    /// Sending a deck command to the audio thread failed because the
    /// SPSC command channel was full (audio thread not draining fast
    /// enough). M10.5.
    #[error("command channel full; retry")]
    CommandChannelFull,

    /// `load_track`/`play`/etc. called before `start_engine` /
    /// `start_thru` succeeded. M10.5.
    #[error("engine is not running; call start_engine first")]
    EngineNotRunning,
}

/// The Apple-side handle to the Dub audio engine.
///
/// Construct one with `DubEngine::new()` (UniFFI emits Swift's
/// `DubEngine()` for this). Methods are all `&self`-on-`Arc<Self>`,
/// so the same handle can be passed across threads and called from
/// the SwiftUI render loop without further synchronization on the
/// Swift side — the internal `Mutex` serialises mutating methods.
///
/// Lifecycle:
///
/// 1. `let engine = DubEngine()`
/// 2. `engine.listInputDevices()` → present the device picker
/// 3. `engine.startThru(deviceName, channels)` → begin capture
/// 4. Render loop polls `peaksLen` + `peaksExtend` for waveform data
/// 5. `engine.stopThru()` on quit (or rely on Swift dropping the
///    last reference; UniFFI's `Drop` impl invokes `stop_thru`
///    automatically)
#[derive(uniffi::Object)]
pub struct DubEngine {
    state: Mutex<EngineState>,
}

/// Internal state machine for the engine.
///
/// `Stopped` is the freshly-constructed, post-`stop_thru`, and
/// post-failed-`start_thru` state. `Running` carries every handle
/// that needs to outlive the audio thread.
enum EngineState {
    Stopped,
    Running(Box<RunningState>),
}

/// Per-deck source of waveform peak data the renderer consumes.
///
/// Two variants for two playback modes:
///
/// * [`PeakSource::Live`] — Thru mode (M9): peaks are streamed off
///   the live audio-thread tap by a [`PeakStream`] analysis thread.
///   The data grows over time as the platter spins.
/// * [`PeakSource::File`] — File mode (M10.5): peaks were computed
///   synchronously off the fully-decoded [`Track`] at load time
///   ([`compute_offline_peaks`]). The data is fixed at the moment
///   of load — `peaks_len` reports `broadband.len()` and never
///   grows again.
///
/// The renderer's FFI methods ([`DubEngine::peaks_extend`],
/// [`DubEngine::peaks_len`], etc.) delegate through this enum so
/// Swift doesn't branch on mode — it just polls
/// `peaks_extend(deck, start_idx)` once per frame and gets the
/// authoritative chunks for whichever mode the deck is in.
enum PeakSource {
    /// Live Thru-mode capture. The `PeakStream`'s analysis thread
    /// reads from an audio-thread `ringbuf` tap and writes new
    /// chunks to a shared `PeakBuffer`.
    ///
    /// The `sample_rate` field is the analysis-side rate (= engine
    /// SR for Thru mode). Stored alongside the stream because
    /// `PeakStream` itself doesn't carry SR.
    Live {
        stream: PeakStream,
        sample_rate: u32,
    },
    /// Pre-computed File-mode peaks. The whole track's broadband +
    /// band peaks were decimated once during `load_track`.
    File(FilePeaks),
}

/// Offline-decoded peak buffer for a File-mode deck.
///
/// Mirrors the *exposed* surface of [`PeakStream`] (chunks, lengths,
/// per-chunk sample counts, sample rate) so the FFI accessors can
/// treat both variants uniformly. The underlying storage is just a
/// pair of `Vec`s — no analysis thread, no SPSC ring, no Drop work
/// at shutdown.
struct FilePeaks {
    broadband: Vec<PeakChunk>,
    bands: Vec<BandPeakChunk>,
    /// Decoded-track sample rate. May differ from the engine SR
    /// (e.g. a 44.1 kHz MP3 played on a 48 kHz output). The renderer
    /// uses this to compute `chunk_duration_secs` (the time-axis
    /// scale factor), so a per-source rate is correct.
    sample_rate: u32,
    samples_per_broadband_chunk: u32,
    samples_per_band_chunk: u32,
}

impl PeakSource {
    fn broadband_len(&self) -> usize {
        match self {
            PeakSource::Live { stream, .. } => stream.len(),
            PeakSource::File(f) => f.broadband.len(),
        }
    }

    fn band_len(&self) -> usize {
        match self {
            PeakSource::Live { stream, .. } => stream.band_len(),
            PeakSource::File(f) => f.bands.len(),
        }
    }

    fn sample_rate(&self) -> u32 {
        match self {
            PeakSource::Live { sample_rate, .. } => *sample_rate,
            PeakSource::File(f) => f.sample_rate,
        }
    }

    fn samples_per_broadband_chunk(&self) -> u32 {
        match self {
            PeakSource::Live { stream, .. } => {
                u32::try_from(stream.samples_per_chunk()).unwrap_or(u32::MAX)
            }
            PeakSource::File(f) => f.samples_per_broadband_chunk,
        }
    }

    fn samples_per_band_chunk(&self) -> Option<u32> {
        match self {
            PeakSource::Live { stream, .. } => stream
                .samples_per_band_chunk()
                .map(|n| u32::try_from(n).unwrap_or(u32::MAX)),
            PeakSource::File(f) => Some(f.samples_per_band_chunk),
        }
    }

    fn extend_broadband_from(&self, start: usize, out: &mut Vec<PeakChunk>) {
        match self {
            PeakSource::Live { stream, .. } => {
                let _new_end = stream.buffer().extend_chunks(start, out);
            }
            PeakSource::File(f) => {
                if start < f.broadband.len() {
                    out.extend_from_slice(&f.broadband[start..]);
                }
            }
        }
    }

    fn extend_band_from(&self, start: usize, out: &mut Vec<BandPeakChunk>) {
        match self {
            PeakSource::Live { stream, .. } => {
                let _new_end = stream.buffer().extend_band_chunks(start, out);
            }
            PeakSource::File(f) => {
                if start < f.bands.len() {
                    out.extend_from_slice(&f.bands[start..]);
                }
            }
        }
    }
}

/// Active audio session. Field order matters for `Drop`:
///
/// 1. `peaks` is dropped first → each `PeakSource::Live` joins its
///    decimator thread cleanly. `PeakSource::File` drops `Vec`s, no
///    threading.
/// 2. `handle` is dropped second → the engine's main-thread proxy
///    releases its trash channels.
/// 3. `output` is dropped third → `AudioOutput::drop` stops the
///    CoreAudio output AudioUnit and reclaims the `Engine` it
///    owned.
/// 4. `input` is dropped last (when present) → no more samples flow.
struct RunningState {
    peaks: [Option<PeakSource>; 2],
    /// Per-deck loaded track (File mode). Held so [`DubEngine::track_info`]
    /// can read metadata after load. The engine's deck also holds a
    /// clone of this `Arc<Track>` — the audio thread reads samples
    /// through its own reference.
    file_tracks: [Option<Arc<Track>>; 2],
    /// Live engine command channel. Held purely so its `Drop` runs
    /// at the right point in the shutdown sequence.
    handle: EngineHandle,
    /// Live CoreAudio output AudioUnit. Held for `Drop`; renderer
    /// never touches it.
    #[allow(dead_code)]
    output: AudioOutput,
    /// Live CoreAudio input AudioUnit. `Some` in Thru mode (M9),
    /// `None` in output-only / File-only mode (M10.5).
    #[allow(dead_code)]
    input: Option<AudioInput>,
    /// Engine sample rate (= output device SR). May differ from a
    /// File-mode track's source SR — the engine resamples on render
    /// (PRD §4.4). File-mode peaks carry their own SR so the
    /// renderer's time-axis math is correct per-deck.
    sample_rate: u32,
}

#[uniffi::export]
impl DubEngine {
    /// Construct a fresh engine handle. The audio system is not
    /// touched yet — `start_thru` does that.
    #[uniffi::constructor]
    #[must_use]
    pub fn new() -> Arc<Self> {
        Arc::new(Self {
            state: Mutex::new(EngineState::Stopped),
        })
    }

    /// Enumerate CoreAudio input devices. Returns just their names;
    /// the Swift picker passes one of these strings back to
    /// [`start_thru`].
    ///
    /// Off-RT; safe to call at any time. Returns an empty list if
    /// CoreAudio enumeration fails for any reason (logged via
    /// `eprintln!`; we don't surface enumeration errors as
    /// `EngineError` because that would force every consumer to
    /// branch on a near-impossible failure).
    #[must_use]
    pub fn list_input_devices(&self) -> Vec<String> {
        match dub_audio::list_input_devices() {
            Ok(devs) => devs.into_iter().map(|d| d.name).collect(),
            Err(e) => {
                eprintln!("dub-ffi: list_input_devices failed: {e}");
                Vec::new()
            }
        }
    }

    /// Begin a Thru session: open the input device by name on the
    /// given 1-based channel pair, start a default-stereo output AU,
    /// and attach a `ThruSource` + `PeakStream` on deck 0.
    ///
    /// `channels` is a pair of 1-based CoreAudio input-channel
    /// indices (e.g. `[3, 4]` for the canonical SL3 timecode pair).
    ///
    /// # Errors
    ///
    /// * [`EngineError::AlreadyRunning`] if the engine is already in
    ///   `Running` state. Call `stop_thru` first.
    /// * [`EngineError::InvalidChannels`] if `channels.len() != 2`
    ///   or any channel index is `0` (the FFI uses 1-based indices
    ///   to stay consistent with the CLI).
    /// * [`EngineError::DeviceNotFound`] if no input device matches
    ///   `device_name`.
    /// * [`EngineError::AudioStartFailed`] for any other CoreAudio
    ///   open / attach failure.
    pub fn start_thru(&self, device_name: String, channels: Vec<u32>) -> Result<(), EngineError> {
        let mut state = lock_state(&self.state);
        if matches!(*state, EngineState::Running(_)) {
            return Err(EngineError::AlreadyRunning);
        }

        if channels.len() != 2 || channels.contains(&0) {
            return Err(EngineError::InvalidChannels(channels));
        }

        let running = start_thru_inner(&device_name, &channels, None)?;
        *state = EngineState::Running(Box::new(running));
        Ok(())
    }

    /// Begin a **two-deck** Thru session: open the input device on
    /// the combined 4-channel set (deck A pair + deck B pair), demux
    /// in the IOProc into two stereo SPSC rings, and attach a
    /// `ThruSource` + `PeakStream` on both deck 0 and deck 1.
    ///
    /// The renderer can then poll `peaks_len(0)` / `peaks_len(1)`
    /// independently and show one waveform per deck.
    ///
    /// `channels_a` and `channels_b` are each 1-based pairs (e.g.
    /// `channels_a = [3, 4]`, `channels_b = [5, 6]` for the canonical
    /// SL3 two-deck layout). Channels must not overlap.
    ///
    /// # Errors
    ///
    /// Same as [`start_thru`] for the deck A pair, plus:
    /// * [`EngineError::InvalidChannels`] if `channels_b.len() != 2`,
    ///   any index is `0`, or the A/B pairs share a channel.
    pub fn start_thru_two_deck(
        &self,
        device_name: String,
        channels_a: Vec<u32>,
        channels_b: Vec<u32>,
    ) -> Result<(), EngineError> {
        let mut state = lock_state(&self.state);
        if matches!(*state, EngineState::Running(_)) {
            return Err(EngineError::AlreadyRunning);
        }

        if channels_a.len() != 2 || channels_a.contains(&0) {
            return Err(EngineError::InvalidChannels(channels_a));
        }
        if channels_b.len() != 2 || channels_b.contains(&0) {
            return Err(EngineError::InvalidChannels(channels_b));
        }
        // No channel may appear in both pairs.
        if channels_a.iter().any(|c| channels_b.contains(c)) {
            let mut combined = channels_a;
            combined.extend(channels_b);
            return Err(EngineError::InvalidChannels(combined));
        }

        let running = start_thru_inner(&device_name, &channels_a, Some(&channels_b))?;
        *state = EngineState::Running(Box::new(running));
        Ok(())
    }

    /// Tear down the Thru session. Idempotent — calling `stop_thru`
    /// on an already-stopped engine is a no-op (no error).
    pub fn stop_thru(&self) {
        let mut state = lock_state(&self.state);
        // Move out the running state so its drop order runs while
        // the mutex is held. Dropping the inner state runs the
        // shutdown sequence documented on `RunningState`.
        let prev = std::mem::replace(&mut *state, EngineState::Stopped);
        drop(prev);
    }

    /// Alias of [`Self::stop_thru`] for parity with the M10.5
    /// `start_engine` naming. Same idempotent semantics: tears the
    /// session down regardless of whether it was started in Thru,
    /// two-deck-Thru, or output-only mode.
    pub fn stop_engine(&self) {
        self.stop_thru();
    }

    /// Start an **output-only** engine session (M10.5).
    ///
    /// No input device is opened — the engine renders whatever the
    /// decks output (File mode) and nothing else. Use this when a
    /// timecode interface is not available and the DJ wants to
    /// drag-and-drop tracks onto decks for casual playback / track
    /// preparation (PRD §6.1.3).
    ///
    /// `output_channels` is the number of physical output channels
    /// to open the AU with. Pass `2` for stereo (built-in speakers,
    /// headphones); pass `4` to mirror the canonical SL3 layout
    /// (deck A → ch 1+2, deck B → ch 3+4) so a follow-up
    /// `start_thru_two_deck` call from the same UI gives consistent
    /// physical routing. Output device is the system default; choose
    /// via Audio MIDI Setup (PRD §10).
    ///
    /// After success, the deck count is `dub_engine::DECK_COUNT` (= 2);
    /// each deck starts empty (no peaks, no track). Call
    /// [`Self::load_track`] to populate.
    ///
    /// # Errors
    ///
    /// * [`EngineError::AlreadyRunning`] if a session is already
    ///   active.
    /// * [`EngineError::InvalidChannels`] if `output_channels < 2`.
    /// * [`EngineError::AudioStartFailed`] for any CoreAudio
    ///   open/start failure.
    pub fn start_engine(&self, output_channels: u32) -> Result<(), EngineError> {
        let mut state = lock_state(&self.state);
        if matches!(*state, EngineState::Running(_)) {
            return Err(EngineError::AlreadyRunning);
        }
        if output_channels < 2 {
            return Err(EngineError::InvalidChannels(vec![output_channels]));
        }

        let running = start_engine_inner(output_channels)?;
        *state = EngineState::Running(Box::new(running));
        Ok(())
    }

    /// Load a track on the given deck (M10.5).
    ///
    /// Synchronously decodes the file at `path` via
    /// [`dub_io::Track::load_from_path`], computes the whole-track
    /// peaks via [`compute_offline_peaks`], stores them in the
    /// per-deck [`PeakSource::File`], and sends
    /// `Command::DeckLoad` to the audio thread. Position is reset
    /// to `0.0` and the deck starts in the paused state — the
    /// caller is expected to follow up with [`Self::play`].
    ///
    /// Off-RT: decoding a typical 4-minute MP3 takes ~50 ms on
    /// Apple silicon; offline peaks are another ~20 ms. Both are
    /// done on the calling thread (UniFFI marshals the call from
    /// Swift's main actor), which is fine because the audio thread
    /// is not blocked — it continues rendering silence on the deck
    /// until the `Command::DeckLoad` is dequeued.
    ///
    /// # Errors
    ///
    /// * [`EngineError::EngineNotRunning`] if `start_engine` /
    ///   `start_thru` hasn't been called.
    /// * [`EngineError::InvalidDeckIndex`] if `deck_idx >=
    ///   DECK_COUNT`.
    /// * [`EngineError::TrackDecodeFailed`] for any IO / codec /
    ///   layout / empty-decode failure.
    /// * [`EngineError::CommandChannelFull`] if the audio thread is
    ///   not draining commands (implausible in normal operation —
    ///   the channel is sized for hundreds of pending commands).
    pub fn load_track(&self, deck_idx: u64, path: String) -> Result<(), EngineError> {
        let idx = deck_idx_to_usize(deck_idx)?;
        let mut state = lock_state(&self.state);
        let EngineState::Running(running) = &mut *state else {
            return Err(EngineError::EngineNotRunning);
        };

        let track = Track::load_from_path(&path)
            .map_err(|e| EngineError::TrackDecodeFailed(format!("{path}: {e}")))?;
        let track = Arc::new(track);

        let OfflinePeaks {
            broadband,
            bands,
            sample_rate,
            samples_per_broadband_chunk,
            samples_per_band_chunk,
        } = compute_offline_peaks(track.samples(), track.sample_rate(), track.channels())
            .map_err(|e| EngineError::TrackDecodeFailed(format!("peaks: {e}")))?;

        running
            .handle
            .deck(idx)
            .load(track.clone())
            .map_err(|(e, _arc)| match e {
                dub_engine::CommandError::ChannelFull => EngineError::CommandChannelFull,
                dub_engine::CommandError::InvalidDeck { idx, .. } => {
                    EngineError::InvalidDeckIndex(u64::from(idx))
                }
            })?;

        running.file_tracks[idx] = Some(track);
        running.peaks[idx] = Some(PeakSource::File(FilePeaks {
            broadband,
            bands,
            sample_rate,
            samples_per_broadband_chunk: u32::try_from(samples_per_broadband_chunk)
                .unwrap_or(u32::MAX),
            samples_per_band_chunk: u32::try_from(samples_per_band_chunk).unwrap_or(u32::MAX),
        }));

        Ok(())
    }

    /// Start playback on the given deck (M10.5).
    ///
    /// In File mode, advances the playhead at unity rate from its
    /// current position. In Thru mode, this is a no-op at the engine
    /// level (the timecode carrier drives the rate) but sent
    /// anyway so the deck's `is_playing` flag is consistent with the
    /// UI. Idempotent: playing an already-playing deck is harmless.
    ///
    /// # Errors
    ///
    /// See [`Self::load_track`] for the error model; same variants
    /// apply.
    pub fn play(&self, deck_idx: u64) -> Result<(), EngineError> {
        let idx = deck_idx_to_usize(deck_idx)?;
        let mut state = lock_state(&self.state);
        let EngineState::Running(running) = &mut *state else {
            return Err(EngineError::EngineNotRunning);
        };
        running.handle.deck(idx).play().map_err(map_command_error)
    }

    /// Pause playback on the given deck (M10.5).
    ///
    /// File mode freezes the playhead at its current position.
    /// Position can be resumed with [`Self::play`] or jumped with
    /// [`Self::seek`].
    ///
    /// # Errors
    ///
    /// Same as [`Self::play`].
    pub fn pause(&self, deck_idx: u64) -> Result<(), EngineError> {
        let idx = deck_idx_to_usize(deck_idx)?;
        let mut state = lock_state(&self.state);
        let EngineState::Running(running) = &mut *state else {
            return Err(EngineError::EngineNotRunning);
        };
        running.handle.deck(idx).pause().map_err(map_command_error)
    }

    /// Seek to the given time position on the deck (M10.5).
    ///
    /// `position_secs` is the wall-clock offset from track start.
    /// Negative values and values past the end are allowed — the
    /// engine renders silence and keeps advancing, mirroring a real
    /// record being lifted off the platter. The actual frame
    /// position is `position_secs × track.sample_rate()`; rounding
    /// is to the nearest frame.
    ///
    /// # Errors
    ///
    /// Same as [`Self::play`].
    pub fn seek(&self, deck_idx: u64, position_secs: f64) -> Result<(), EngineError> {
        let idx = deck_idx_to_usize(deck_idx)?;
        let mut state = lock_state(&self.state);
        let EngineState::Running(running) = &mut *state else {
            return Err(EngineError::EngineNotRunning);
        };

        // Convert seconds → track frames using the loaded track's
        // SR (not the engine SR). If no track is loaded, we still
        // send the command (engine treats it as out-of-range silence)
        // so the UI doesn't have to special-case empty decks.
        let position_frames = match running.file_tracks[idx].as_ref() {
            #[allow(clippy::cast_precision_loss)]
            Some(track) => position_secs * f64::from(track.sample_rate()),
            None => position_secs,
        };

        running
            .handle
            .deck(idx)
            .seek(position_frames)
            .map_err(map_command_error)
    }

    /// Read the current playhead position on the deck (M10.5).
    ///
    /// Returns a [`PositionInfo`] with elapsed seconds, remaining
    /// seconds, total duration, and the deck's transport state.
    /// All fields are zero when the engine is stopped or the deck
    /// is empty.
    ///
    /// Cheap: a few `Relaxed` atomic loads. Safe to call from a
    /// 30 Hz / 60 Hz UI loop without rate-limiting.
    #[must_use]
    pub fn position(&self, deck_idx: u64) -> PositionInfo {
        let idx = match deck_idx_to_usize(deck_idx) {
            Ok(idx) => idx,
            Err(_) => return PositionInfo::EMPTY,
        };
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return PositionInfo::EMPTY;
        };
        let Some(snap) = running.handle.deck_state(idx) else {
            return PositionInfo::EMPTY;
        };
        let Some(track) = running.file_tracks[idx].as_ref() else {
            return PositionInfo {
                has_track: false,
                is_playing: snap.is_playing,
                ..PositionInfo::EMPTY
            };
        };
        let sr = f64::from(track.sample_rate());
        let duration_secs = if sr > 0.0 {
            #[allow(clippy::cast_precision_loss)]
            let total_frames = track.frames() as f64;
            total_frames / sr
        } else {
            0.0
        };
        let elapsed_secs = if sr > 0.0 {
            (snap.position_frames / sr).max(0.0).min(duration_secs)
        } else {
            0.0
        };
        let remaining_secs = (duration_secs - elapsed_secs).max(0.0);
        PositionInfo {
            elapsed_secs,
            remaining_secs,
            duration_secs,
            is_playing: snap.is_playing,
            at_end: snap.at_end,
            has_track: true,
        }
    }

    /// Read metadata for the currently-loaded File-mode track on the
    /// deck (M10.5).
    ///
    /// Returns `None` if no track is loaded or the engine is stopped.
    ///
    /// Title / artist are best-effort placeholders today (the file
    /// stem) — M11 library import will populate them from
    /// Serato/Traktor/rekordbox tags or symphonia metadata.
    #[must_use]
    pub fn track_info(&self, deck_idx: u64) -> Option<TrackInfo> {
        let idx = deck_idx_to_usize(deck_idx).ok()?;
        let state = lock_state(&self.state);
        let running = state.as_running()?;
        let track = running.file_tracks[idx].as_ref()?;
        Some(TrackInfo {
            title: String::new(),
            artist: String::new(),
            duration_secs: track.duration_seconds(),
            sample_rate: track.sample_rate(),
            channels: u32::from(track.channels()),
            bpm: track.bpm(),
        })
    }

    /// Number of broadband [`PeakChunk`]s captured so far on `deck_idx`.
    ///
    /// Returns `0` if the engine is stopped or the deck has no
    /// peaks stream. Cheap (lock-free `AtomicUsize` load after the
    /// state mutex acquire).
    #[must_use]
    pub fn peaks_len(&self, deck_idx: u64) -> u64 {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return 0;
        };
        let Some(source) = peak_source_for(running, deck_idx) else {
            return 0;
        };
        source.broadband_len() as u64
    }

    /// Wall-clock duration of one [`PeakChunk`] on `deck_idx`, in
    /// seconds. `samples_per_chunk / sample_rate`. Returns `0.0`
    /// when stopped / unknown deck — Swift uses the result as a
    /// time-axis scale factor, and a zero scale produces a sane
    /// empty waveform rather than NaN.
    ///
    /// Mode-aware: in Thru mode the rate is the engine SR (= input
    /// device SR); in File mode the rate is the loaded track's SR
    /// (may differ from output device SR — the engine resamples on
    /// render, but peaks are at source-rate cadence).
    #[must_use]
    pub fn peaks_chunk_duration_secs(&self, deck_idx: u64) -> f64 {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return 0.0;
        };
        let Some(source) = peak_source_for(running, deck_idx) else {
            return 0.0;
        };
        let sr = source.sample_rate();
        if sr == 0 {
            return 0.0;
        }
        f64::from(source.samples_per_broadband_chunk()) / f64::from(sr)
    }

    /// Fetch new [`PeakChunk`]s captured since `start_idx`,
    /// serialised as a raw byte buffer suitable for direct upload
    /// to a `MTLBuffer`. The Swift side reinterprets each 12-byte
    /// stride as a `(f32 min, f32 max, f32 rms)` triple.
    ///
    /// Caller cache-discipline: after each call, Swift advances
    /// its `start_idx` by `bytes.count / 12`. `peaks_len` is the
    /// authoritative total; this method's return covers
    /// `[start_idx, peaks_len)`.
    ///
    /// Returns an empty `Vec` when the engine is stopped, the deck
    /// has no peaks source, or `start_idx >= len()`.
    #[must_use]
    pub fn peaks_extend(&self, deck_idx: u64, start_idx: u64) -> Vec<u8> {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return Vec::new();
        };
        let Some(source) = peak_source_for(running, deck_idx) else {
            return Vec::new();
        };
        let mut chunks: Vec<PeakChunk> = Vec::new();
        source.extend_broadband_from(usize_from_u64(start_idx), &mut chunks);
        peak_chunks_to_bytes(&chunks)
    }

    /// Number of [`BandPeakChunk`]s captured so far on `deck_idx`.
    /// Returns `0` if band capture is disabled or the engine is
    /// stopped.
    #[must_use]
    pub fn band_peaks_len(&self, deck_idx: u64) -> u64 {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return 0;
        };
        let Some(source) = peak_source_for(running, deck_idx) else {
            return 0;
        };
        source.band_len() as u64
    }

    /// Wall-clock duration of one [`BandPeakChunk`] on `deck_idx`,
    /// in seconds. Equals `BAND_SAMPLES_PER_CHUNK / sample_rate`.
    /// Returns `0.0` if band capture is disabled, the engine is
    /// stopped, or the deck has no stream.
    #[must_use]
    pub fn band_peaks_chunk_duration_secs(&self, deck_idx: u64) -> f64 {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return 0.0;
        };
        let Some(source) = peak_source_for(running, deck_idx) else {
            return 0.0;
        };
        let Some(spbc) = source.samples_per_band_chunk() else {
            return 0.0;
        };
        let sr = source.sample_rate();
        if sr == 0 {
            return 0.0;
        }
        f64::from(spbc) / f64::from(sr)
    }

    /// Current audio sample rate the engine is running at, in Hz.
    /// Returns `0` when the engine is stopped.
    ///
    /// M10.1 renderers use this to derive `samplesPerChunk` from
    /// `peaks_chunk_duration_secs` — `dur × sample_rate` is the
    /// exact integer cadence the GPU shader needs to map between
    /// the broadband and band rings.
    #[must_use]
    pub fn sample_rate(&self) -> u32 {
        let state = lock_state(&self.state);
        state.as_running().map_or(0, |r| r.sample_rate)
    }

    /// Fetch new [`BandPeakChunk`]s captured since `start_idx`,
    /// serialised as bytes (8 × `f32` per chunk = 32 bytes stride).
    /// Used by the M10.1 multi-colour shader.
    ///
    /// Returns an empty `Vec` when band capture is disabled, the
    /// engine is stopped, or `start_idx >= band_len()`.
    #[must_use]
    pub fn band_peaks_extend(&self, deck_idx: u64, start_idx: u64) -> Vec<u8> {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return Vec::new();
        };
        let Some(source) = peak_source_for(running, deck_idx) else {
            return Vec::new();
        };
        let mut chunks: Vec<BandPeakChunk> = Vec::new();
        source.extend_band_from(usize_from_u64(start_idx), &mut chunks);
        band_peak_chunks_to_bytes(&chunks)
    }
}

impl EngineState {
    fn as_running(&self) -> Option<&RunningState> {
        match self {
            EngineState::Running(running) => Some(running.as_ref()),
            EngineState::Stopped => None,
        }
    }
}

/// Snapshot of a deck's playhead state in wall-clock seconds.
///
/// All fields are zero for an empty / stopped deck (`has_track =
/// false`). Returned by [`DubEngine::position`].
#[derive(Debug, Clone, uniffi::Record)]
pub struct PositionInfo {
    /// Wall-clock seconds elapsed from track start (≥ 0, ≤ duration).
    pub elapsed_secs: f64,
    /// Wall-clock seconds remaining until track end (≥ 0).
    pub remaining_secs: f64,
    /// Wall-clock total track duration (= `track.frames /
    /// track.sample_rate`).
    pub duration_secs: f64,
    /// Whether the deck is currently advancing the playhead.
    pub is_playing: bool,
    /// Whether the playhead is past the end of the track. UI uses
    /// this to clear a "now playing" badge.
    pub at_end: bool,
    /// `true` if a File-mode track is loaded on this deck. `false`
    /// for empty decks and Thru-mode-only decks (where the
    /// "position" concept doesn't apply because the timecode
    /// drives the rate).
    pub has_track: bool,
}

impl PositionInfo {
    const EMPTY: Self = Self {
        elapsed_secs: 0.0,
        remaining_secs: 0.0,
        duration_secs: 0.0,
        is_playing: false,
        at_end: false,
        has_track: false,
    };
}

/// Metadata for a File-mode loaded track (M10.5).
///
/// Returned by [`DubEngine::track_info`]. Title / artist are
/// best-effort and may be empty in M10.5 (M11 will plumb them from
/// library metadata or codec tags).
#[derive(Debug, Clone, uniffi::Record)]
pub struct TrackInfo {
    /// Track title. Empty in M10.5 (M11 plumbs this from library /
    /// codec metadata).
    pub title: String,
    /// Artist. Empty in M10.5; same plumbing target as `title`.
    pub artist: String,
    /// Total duration in seconds.
    pub duration_secs: f64,
    /// Source sample rate (may differ from engine SR).
    pub sample_rate: u32,
    /// 1 (mono) or 2 (stereo).
    pub channels: u32,
    /// BPM annotation, if BPM analysis has been run on the track.
    /// `None` in M10.5 (M11 / M11.5 will run analysis at load time
    /// or pull from the library).
    pub bpm: Option<f64>,
}

/// Helper: lock the engine-state mutex, recovering from a poisoned
/// lock by extracting the inner data. Poisoning can only happen if
/// a UniFFI-exported method panics mid-mutation; since we forbid
/// panics across the boundary, this branch is theoretical, but we
/// handle it defensively so Swift never sees a panic propagated
/// from a `.unwrap()` on `lock()`.
fn lock_state(state: &Mutex<EngineState>) -> std::sync::MutexGuard<'_, EngineState> {
    state
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner)
}

fn peak_source_for(running: &RunningState, deck_idx: u64) -> Option<&PeakSource> {
    let idx: usize = deck_idx.try_into().ok()?;
    running.peaks.get(idx).and_then(|s| s.as_ref())
}

fn deck_idx_to_usize(deck_idx: u64) -> Result<usize, EngineError> {
    let idx: usize = deck_idx
        .try_into()
        .map_err(|_| EngineError::InvalidDeckIndex(deck_idx))?;
    if idx >= dub_engine::DECK_COUNT {
        return Err(EngineError::InvalidDeckIndex(deck_idx));
    }
    Ok(idx)
}

/// Saturating conversion from u64 (UniFFI-friendly) to usize. On
/// 64-bit targets (the only ones we ship to) this is the identity;
/// the saturate guards against a misbehaving Swift caller passing
/// `UInt64.max` to a `start_idx`. Behaviour in that case is "treat
/// it as already past the end and return empty", which matches what
/// `PeakBuffer::extend_chunks` already does for `start_idx >= len`.
fn usize_from_u64(v: u64) -> usize {
    usize::try_from(v).unwrap_or(usize::MAX)
}

/// Open the input device, build the engine, and attach a Thru
/// source on deck 0 with peaks + band capture. Returns the full
/// [`RunningState`] on success.
///
/// Pulled out of `start_thru` so the `Mutex` guard stays narrow:
/// this function never touches `self.state`, only the audio
/// subsystem.
fn start_thru_inner(
    device_name: &str,
    channels_a: &[u32],
    channels_b: Option<&[u32]>,
) -> Result<RunningState, EngineError> {
    // ----- 1. Build InputOptions ------------------------------------
    // Convert 1-based user-facing channel indices to 0-based
    // CoreAudio channel_map. Validation in `start_thru` /
    // `start_thru_two_deck` ensures we have valid channels.
    //
    // Two-deck mode (`channels_b = Some`): open the AU with 4
    // physical channels and use `output_pairs` to demux into two
    // stereo SPSC consumers — pair 0 = deck A, pair 1 = deck B.
    // This is the same M5.6 two-deck-timecode setup, repurposed
    // for two-deck Thru.
    #[allow(clippy::cast_possible_truncation, clippy::cast_possible_wrap)]
    let mut channel_map: Vec<i32> = channels_a.iter().map(|&c| (c as i32) - 1).collect();
    let mut output_pairs: Option<Vec<(u32, u32)>> = None;
    if let Some(chs_b) = channels_b {
        #[allow(clippy::cast_possible_truncation, clippy::cast_possible_wrap)]
        let b_zero: Vec<i32> = chs_b.iter().map(|&c| (c as i32) - 1).collect();
        channel_map.extend(b_zero);
        // Pair 0 = AU outputs 0+1 (deck A), pair 1 = AU outputs 2+3
        // (deck B). Order is fixed by how we appended above.
        output_pairs = Some(vec![(0, 1), (2, 3)]);
    }
    let input_channels = u32::try_from(channel_map.len()).unwrap_or(2);
    let input_opts = InputOptions {
        device_name: Some(device_name.to_string()),
        channels: input_channels,
        channel_map: Some(channel_map),
        output_pairs,
        ..InputOptions::default()
    };

    // ----- 2. Open input device -------------------------------------
    let mut input = AudioInput::start_with_options(&input_opts)
        .map_err(|e| classify_audio_error(e, device_name))?;
    let input_sr_f32 = input.sample_rate();
    #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
    let input_sr = input_sr_f32 as u32;

    // ----- 3. Take consumers for the configured deck(s) ------------
    let consumer_a = input.take_consumer_pair(0).ok_or_else(|| {
        EngineError::AudioStartFailed("input pair 0 consumer already taken".to_string())
    })?;
    let consumer_b = if channels_b.is_some() {
        Some(input.take_consumer_pair(1).ok_or_else(|| {
            EngineError::AudioStartFailed("input pair 1 consumer already taken".to_string())
        })?)
    } else {
        None
    };

    // ----- 4. Build engine ------------------------------------------
    let (engine, mut handle) = Engine::new_with_handle(input_sr_f32, ENGINE_BLOCK_FRAMES);

    // ----- 5. Open output (internal-mixer routing for M10) ----------
    let output_opts = OutputOptions {
        channels: 2,
        ..OutputOptions::default()
    };
    let output = AudioOutput::start_with_options(engine, &output_opts, INTERNAL_MIXER_ROUTING)
        .map_err(|e| EngineError::AudioStartFailed(format!("starting output: {e}")))?;

    // ----- 6. Attach Thru source(s) + peaks on each deck -----------
    let thru_cfg = ThruInputConfig {
        max_block_frames: THRU_MAX_BLOCK_FRAMES,
        input_sample_rate: input_sr_f32,
    };
    let mut peaks: [Option<PeakSource>; 2] = [None, None];

    let peaks_cfg_a = PeakStreamConfig::at(input_sr);
    let peaks_stream_a = handle
        .attach_thru_source_with_peaks_tracking(0, consumer_a, thru_cfg, peaks_cfg_a)
        .map_err(|e| EngineError::AudioStartFailed(format!("attaching thru on deck 0: {e}")))?;
    peaks[0] = Some(PeakSource::Live {
        stream: peaks_stream_a,
        sample_rate: input_sr,
    });

    if let Some(consumer_b) = consumer_b {
        let peaks_cfg_b = PeakStreamConfig::at(input_sr);
        let peaks_stream_b = handle
            .attach_thru_source_with_peaks_tracking(1, consumer_b, thru_cfg, peaks_cfg_b)
            .map_err(|e| EngineError::AudioStartFailed(format!("attaching thru on deck 1: {e}")))?;
        peaks[1] = Some(PeakSource::Live {
            stream: peaks_stream_b,
            sample_rate: input_sr,
        });
    }

    Ok(RunningState {
        peaks,
        file_tracks: [None, None],
        handle,
        output,
        input: Some(input),
        sample_rate: input_sr,
    })
}

/// Map a `dub_audio::AudioError` to the right [`EngineError`]
/// variant based on its content. The HAL doesn't carry typed error
/// kinds for "device not found" vs other failures, so we
/// substring-match its `Display` output. Brittle but contained — if
/// the HAL ever switches to typed errors, this function is the
/// single place that needs to update.
fn classify_audio_error(err: dub_audio::AudioError, device_name: &str) -> EngineError {
    let msg = err.to_string();
    if msg.contains("no input device") || msg.contains("device not found") {
        EngineError::DeviceNotFound(device_name.to_string())
    } else {
        EngineError::AudioStartFailed(msg)
    }
}

/// Open an output AU only — no input, no Thru. Used by
/// [`DubEngine::start_engine`] for the M10.5 File-mode-only path.
fn start_engine_inner(output_channels: u32) -> Result<RunningState, EngineError> {
    // We don't know the output device's SR ahead of time. The
    // existing `start_thru_inner` flow uses the *input* device's SR
    // as the engine SR; for output-only we follow the same
    // convention but read the *output* device's SR instead. Open
    // the AU first with the engine constructed at the system default
    // SR, then read back the actual rate.
    //
    // Simpler approach: build the engine at a placeholder SR
    // (48 kHz, the macOS factory default for built-in output) and
    // let `AudioOutput::start_with_options` align the device to it.
    // If the device refuses, we surface AudioStartFailed.
    const DEFAULT_OUTPUT_SR: f32 = 48_000.0;
    let (engine, handle) = Engine::new_with_handle(DEFAULT_OUTPUT_SR, ENGINE_BLOCK_FRAMES);

    let output_opts = OutputOptions {
        channels: output_channels,
        ..OutputOptions::default()
    };
    let output = AudioOutput::start_with_options(engine, &output_opts, INTERNAL_MIXER_ROUTING)
        .map_err(|e| EngineError::AudioStartFailed(format!("starting output: {e}")))?;

    #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
    let sample_rate = output.sample_rate() as u32;

    Ok(RunningState {
        peaks: [None, None],
        file_tracks: [None, None],
        handle,
        output,
        input: None,
        sample_rate,
    })
}

/// Translate `dub_engine::CommandError` (audio-thread feedback
/// channel saturated, bad deck index) into the FFI-surface
/// equivalent. Pulled out to keep the per-method bodies tidy.
fn map_command_error(e: dub_engine::CommandError) -> EngineError {
    match e {
        dub_engine::CommandError::ChannelFull => EngineError::CommandChannelFull,
        dub_engine::CommandError::InvalidDeck { idx, .. } => {
            EngineError::InvalidDeckIndex(u64::from(idx))
        }
    }
}

/// Serialise broadband peak chunks to a packed little-endian byte
/// buffer matching `#[repr(C)] PeakChunk` (12 bytes per chunk:
/// three `f32` LE).
///
/// Swift reads this as `Data` and reinterprets via
/// `withUnsafeBytes(_:)` into `[PeakChunk]`. Native-endian works
/// because both ARM64 and x86_64 macOS are little-endian.
fn peak_chunks_to_bytes(chunks: &[PeakChunk]) -> Vec<u8> {
    let mut bytes = Vec::with_capacity(std::mem::size_of_val(chunks));
    for c in chunks {
        bytes.extend_from_slice(&c.min.to_le_bytes());
        bytes.extend_from_slice(&c.max.to_le_bytes());
        bytes.extend_from_slice(&c.rms.to_le_bytes());
    }
    bytes
}

/// Serialise per-band peak chunks to a packed little-endian byte
/// buffer matching `#[repr(C)] BandPeakChunk` (32 bytes per chunk:
/// eight `f32` LE).
fn band_peak_chunks_to_bytes(chunks: &[BandPeakChunk]) -> Vec<u8> {
    let mut bytes = Vec::with_capacity(std::mem::size_of_val(chunks));
    for c in chunks {
        for v in c.rms_per_band {
            bytes.extend_from_slice(&v.to_le_bytes());
        }
    }
    bytes
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ffi_version_is_five_after_m105_file_playback() {
        // Bump tripwire: M10-A 1→2 (DubEngine), M10.1 2→3
        // (sample_rate), M10.2 3→4 (start_thru_two_deck), M10.5 4→5
        // (start_engine, load_track, play, pause, seek, position,
        // track_info, PositionInfo + TrackInfo records).
        assert_eq!(FFI_VERSION, 5);
    }

    #[test]
    fn load_track_on_stopped_engine_returns_not_running() {
        let engine = DubEngine::new();
        let err = engine
            .load_track(0, "/nonexistent.wav".to_string())
            .unwrap_err();
        assert!(matches!(err, EngineError::EngineNotRunning), "got {err:?}");
    }

    #[test]
    fn play_pause_seek_on_stopped_engine_return_not_running() {
        let engine = DubEngine::new();
        for f in [engine.play(0), engine.pause(0), engine.seek(0, 30.0)] {
            assert!(matches!(f.unwrap_err(), EngineError::EngineNotRunning));
        }
    }

    #[test]
    fn load_track_with_invalid_deck_index_returns_invalid_deck() {
        let engine = DubEngine::new();
        // Stopped engine: EngineNotRunning is checked first only after
        // the deck index validates. We check `deck_idx_to_usize` happens
        // first so a clearly-bad deck idx surfaces as InvalidDeckIndex.
        let err = engine.load_track(99, "/tmp/x.wav".to_string()).unwrap_err();
        assert!(matches!(err, EngineError::InvalidDeckIndex(99)));
    }

    #[test]
    fn position_on_stopped_engine_returns_empty() {
        let engine = DubEngine::new();
        let p = engine.position(0);
        assert_eq!(p.elapsed_secs, 0.0);
        assert_eq!(p.duration_secs, 0.0);
        assert_eq!(p.remaining_secs, 0.0);
        assert!(!p.is_playing);
        assert!(!p.has_track);
    }

    #[test]
    fn track_info_on_stopped_engine_returns_none() {
        let engine = DubEngine::new();
        assert!(engine.track_info(0).is_none());
        assert!(engine.track_info(1).is_none());
    }

    #[test]
    fn start_engine_rejects_zero_one_output_channels() {
        let engine = DubEngine::new();
        let err = engine.start_engine(0).unwrap_err();
        assert!(matches!(err, EngineError::InvalidChannels(_)));
        let err = engine.start_engine(1).unwrap_err();
        assert!(matches!(err, EngineError::InvalidChannels(_)));
    }

    #[test]
    fn sample_rate_is_zero_when_stopped() {
        let engine = DubEngine::new();
        assert_eq!(engine.sample_rate(), 0);
    }

    #[test]
    fn greeting_matches() {
        assert_eq!(greeting(), "Dub engine OK");
    }

    #[test]
    fn engine_version_matches_crate() {
        assert_eq!(engine_version(), dub_engine::VERSION);
    }

    #[test]
    fn fresh_engine_reports_no_peaks() {
        let engine = DubEngine::new();
        // No deck has any chunks; idx out of range also returns 0.
        assert_eq!(engine.peaks_len(0), 0);
        assert_eq!(engine.peaks_len(1), 0);
        assert_eq!(engine.peaks_len(99), 0);
        // Extend on a stopped engine is empty (never panics).
        assert!(engine.peaks_extend(0, 0).is_empty());
        assert!(engine.band_peaks_extend(0, 0).is_empty());
        #[allow(clippy::float_cmp)]
        {
            assert_eq!(engine.peaks_chunk_duration_secs(0), 0.0);
            assert_eq!(engine.band_peaks_chunk_duration_secs(0), 0.0);
        }
    }

    #[test]
    fn stop_thru_is_idempotent_on_stopped_engine() {
        let engine = DubEngine::new();
        engine.stop_thru();
        engine.stop_thru();
        // Still stopped, still functional.
        assert_eq!(engine.peaks_len(0), 0);
    }

    #[test]
    fn start_thru_two_deck_rejects_invalid_or_overlapping_channels() {
        let engine = DubEngine::new();
        // Wrong arity on deck A.
        let err = engine
            .start_thru_two_deck("MacBook Pro Microphone".to_string(), vec![], vec![3, 4])
            .unwrap_err();
        assert!(matches!(err, EngineError::InvalidChannels(_)));
        // Wrong arity on deck B.
        let err = engine
            .start_thru_two_deck("MacBook Pro Microphone".to_string(), vec![1, 2], vec![3])
            .unwrap_err();
        assert!(matches!(err, EngineError::InvalidChannels(_)));
        // Zero index rejected (1-based).
        let err = engine
            .start_thru_two_deck("MacBook Pro Microphone".to_string(), vec![1, 2], vec![0, 3])
            .unwrap_err();
        assert!(matches!(err, EngineError::InvalidChannels(_)));
        // Overlap between A and B is rejected — picking the same
        // physical channel for both decks would silently route the
        // wrong audio.
        let err = engine
            .start_thru_two_deck("MacBook Pro Microphone".to_string(), vec![1, 2], vec![2, 3])
            .unwrap_err();
        match err {
            EngineError::InvalidChannels(combined) => {
                assert_eq!(combined, vec![1, 2, 2, 3]);
            }
            _ => panic!("expected InvalidChannels"),
        }
    }

    #[test]
    fn start_thru_rejects_invalid_channels() {
        let engine = DubEngine::new();

        // Empty / wrong arity.
        let err = engine
            .start_thru("MacBook Pro Microphone".to_string(), vec![])
            .unwrap_err();
        assert!(matches!(err, EngineError::InvalidChannels(_)));
        let err = engine
            .start_thru("MacBook Pro Microphone".to_string(), vec![1, 2, 3])
            .unwrap_err();
        assert!(matches!(err, EngineError::InvalidChannels(_)));

        // Zero is rejected (we use 1-based indices).
        let err = engine
            .start_thru("MacBook Pro Microphone".to_string(), vec![0, 1])
            .unwrap_err();
        assert!(matches!(err, EngineError::InvalidChannels(_)));
    }

    #[test]
    fn peak_chunks_to_bytes_round_trips_one_chunk() {
        let c = PeakChunk {
            min: -0.5,
            max: 0.75,
            rms: 0.6,
        };
        let bytes = peak_chunks_to_bytes(std::slice::from_ref(&c));
        assert_eq!(bytes.len(), 12);
        assert_eq!(f32::from_le_bytes(bytes[0..4].try_into().unwrap()), c.min);
        assert_eq!(f32::from_le_bytes(bytes[4..8].try_into().unwrap()), c.max);
        assert_eq!(f32::from_le_bytes(bytes[8..12].try_into().unwrap()), c.rms);
    }

    #[test]
    fn band_peak_chunks_to_bytes_round_trips_one_chunk() {
        let c = BandPeakChunk {
            rms_per_band: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8],
        };
        let bytes = band_peak_chunks_to_bytes(std::slice::from_ref(&c));
        assert_eq!(bytes.len(), 32);
        for k in 0..8 {
            let off = k * 4;
            let v = f32::from_le_bytes(bytes[off..off + 4].try_into().unwrap());
            #[allow(clippy::cast_precision_loss)]
            let expected = c.rms_per_band[k];
            assert!((v - expected).abs() < 1e-6);
        }
    }

    #[test]
    fn empty_chunks_serialise_to_empty_bytes() {
        assert!(peak_chunks_to_bytes(&[]).is_empty());
        assert!(band_peak_chunks_to_bytes(&[]).is_empty());
    }
}
