//! FFI bindings for the Apple frontend.
//!
//! The Apple shell (`apple/Dub`) links against this crate via the
//! `DubCore.xcframework` that [`scripts/build-xcframework.sh`] produces.
//! Swift bindings are generated by UniFFI in library mode — there is no
//! hand-written `.udl` file; the `#[uniffi::export]` proc macros on
//! Rust items below are the single source of truth.
//!
//! ## Surface
//!
//! * Two free functions for the M0.5 smoke screen: [`greeting`] and
//!   [`engine_version`]. Used by `SmokeScreenView` in the Apple shell.
//! * [`DubEngine`] (M10-A): a stateful handle the Apple shell holds
//!   for the lifetime of a "Thru session". Exposes
//!   - `list_input_devices` (read-only)
//!   - `start_thru` / `stop_thru` (lifecycle)
//!   - `peaks_extend` / `peaks_len` / `peaks_chunk_duration_secs`
//!     (broadband waveform data)
//!   - `band_peaks_extend` / `band_peaks_len` /
//!     `band_peaks_chunk_duration_secs` (M9.5b-shipped 8-band
//!     loudness data — used by the M10.1 multi-colour shader)
//!
//! ## Stability contract
//!
//! All errors are surfaced via [`EngineError`]; no panics ever cross
//! the FFI boundary (`.cursor/rules/ffi.mdc`). All `peaks_*` methods
//! return defensive zero / empty values when the named deck has no
//! capture stream, so the Swift renderer never panics on a stale
//! `start_idx`.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Mutex};

use dub_audio::{AudioInput, AudioOutput, InputOptions, OutputOptions};
// `dub_bpm::analyze_beat_grid` import is intentionally removed
// alongside M10.5p Stage 1's beat-grid disable (see `load_track`
// for the re-enable path). The `BeatGrid` UniFFI Record itself is
// crate-local and doesn't need the upstream `BeatGrid as CoreBeatGrid`
// alias until computation comes back online.
use dub_engine::{Engine, EngineHandle, ThruInputConfig, INTERNAL_MIXER_ROUTING};
use dub_io::{
    read_metadata as read_track_metadata_from_disk, Track, TrackMetadata as IoTrackMetadata,
};
use dub_peaks::{
    compute_offline_peaks, BandPeakChunk, FilteredPeakChunk, OfflinePeaks, OnsetChunk, PeakChunk,
    PeakStream, PeakStreamConfig,
};

// UniFFI scaffolding. Emits the C ABI symbols (component contract,
// metadata symbol, RustBuffer alloc/free) that the generated Swift
// bindings depend on. Must be called exactly once per UniFFI-exporting
// crate.
uniffi::setup_scaffolding!();

/// FFI surface version. Bump when adding or removing exported symbols.
///
/// Not currently exposed via UniFFI — Swift consumers verify ABI
/// compatibility through the bindings file UniFFI generates, which
/// embeds a content-hashed checksum per exported function. This
/// constant is kept as a *Rust-side* tripwire so workspace integration
/// tests can fail loudly if someone bumps the surface without updating
/// the version.
///
/// `3`: M10.1 added [`DubEngine::sample_rate`].
/// `4`: M10.2 added [`DubEngine::start_thru_two_deck`] for deck B
///      wiring.
/// `5`: M10.5 added File-mode playback: `start_engine` (output-only
///      lifecycle), `load_track`, `play`, `pause`, `seek`, `position`,
///      `track_info`. `peaks_extend` / `peaks_len` / etc. now read
///      from either the Thru analysis thread or the offline-decoded
///      peak buffer transparently via the per-deck `PeakSource` enum.
/// `6`: M10.5b added [`DubEngine::peaks_generation`] so the renderer
///      can detect per-deck `PeakSource` swaps (Thru → File on load,
///      File → File on reload) and reset its ring buffer + cadence
///      cache. Without this, the renderer's length-monotonicity
///      heuristic gets stuck rendering stale Thru chunks after a
///      drag-and-drop load in Timecode mode.
/// `7`: M10.5b polish: added [`DubEngine::has_external_audio_interface`]
///      so the Apple shell's auto-detect can decide Timecode-vs-Prep
///      mode at launch *without* enumerating input devices (which
///      would trip macOS's microphone-permission prompt on the
///      built-in mic). Probes transport-type metadata only — no AU
///      instantiation, no input-property reads.
/// `8`: M10.6b added Panic-Play (PRD §6.1.2): new [`DubEngine::panic_play`]
///      and [`DubEngine::cancel_panic_play`] methods, and `PositionInfo`
///      gains an `is_panic_play` field so the existing 30 Hz UI poll
///      picks up the engine's panic state without a separate FFI call.
///      Engine-side: per-deck `PanicPlayState` decouples the deck from
///      timecode-driven transport at a held last-known-velocity, with
///      auto-resume on a clean LFSR re-lock.
/// `9`: M10.5l added the per-hop onset-flux side-channel for the
///      renderer's transient-emphasising bloom + saturation pipeline:
///      new [`DubEngine::onset_peaks_len`],
///      [`DubEngine::onset_peaks_chunk_duration_secs`], and
///      [`DubEngine::onset_peaks_extend`] methods, all mirroring the
///      existing `band_peaks_*` shape but with a 4-byte stride
///      (single `f32` per chunk). Engine-side: `PeakStream` /
///      `compute_offline_peaks` now run an `OnsetDecimator` alongside
///      the existing broadband + band decimators; the per-deck
///      `PeakSource` enum delegates to it the same way it delegates
///      to bands.
/// `10`: M10.5p ("DJ-focused waveform") added the per-track beat
///       grid. `load_track` now runs `dub_bpm::analyze_beat_grid`
///       off-thread and stashes the result on `FilePeaks`; the
///       renderer reads it via the new [`DubEngine::beat_grid`]
///       method (returns [`BeatGrid`] — bpm + confidence + beats +
///       beats_per_bar). Used to draw discrete beat ticks atop the
///       new monochrome envelope and (eventually) gate the kick
///       emphasis to on-grid kicks only.
/// `11`: M10.5r tag-metadata pipeline. `TrackInfo` now returns the
///       title / artist read from container tags (ID3v2 for MP3,
///       MP4 atoms for AAC/ALAC, Vorbis comments for FLAC/OGG, RIFF
///       INFO for WAV). New stateless [`read_track_metadata`] FFI
///       function lets the library / file-browser pull the same
///       tags off-disk without loading the track. New
///       [`TrackMetadata`] Record carries them.
/// `12`: M10.5s mouse-scratch primitive — [`DubEngine::set_deck_rate`]
///       exposes the engine's per-deck `DeckSetRate` command with
///       musical-→-engine SR conversion baked in. Used by the Apple
///       shell's drag-to-scratch state machine on the zoomed
///       waveform to drive the deck's playback rate from mouse
///       velocity (PRD §1 / §6.1 mouse-scrub policy).
///   14. M10.5t — `PositionInfo.playhead_secs_unclamped` added so
///       the Apple shell can render a real platter's lead-in /
///       lead-out groove when a scratch pushes the playhead
///       outside `[0, duration_secs]` (PRD §6.1 / §9.6).
pub const FFI_VERSION: u32 = 14;

/// Returns a static greeting string. The Apple shell calls this on launch
/// to verify it linked the Rust core successfully.
#[uniffi::export]
pub fn greeting() -> String {
    String::from("Dub engine OK")
}

/// Returns the version of the underlying `dub-engine` crate (the
/// `CARGO_PKG_VERSION` baked in at compile time).
#[uniffi::export]
pub fn engine_version() -> String {
    String::from(dub_engine::VERSION)
}

/// Maximum Thru block size, in frames. Mirrors `dub-cli`'s
/// `THRU_MAX_BLOCK_FRAMES` — CoreAudio variable buffers can reach
/// ~4096 frames per IOProc on certain devices, and `ThruSource`'s
/// debug assertion enforces this ceiling so a bigger callback would
/// panic on attach. Sized 1 KiB above CoreAudio's known worst case so
/// any future driver expansion doesn't tip us over silently.
const THRU_MAX_BLOCK_FRAMES: usize = 5120;

/// Engine block size in frames, used when constructing the audio
/// graph. 256 matches the `dub-cli` default and gives a good balance
/// between latency (5.3 ms at 48 kHz) and scheduling overhead.
const ENGINE_BLOCK_FRAMES: usize = 256;

/// Errors surfaced across the UniFFI boundary.
///
/// `flat_error` because most variants don't carry structured data
/// the Swift side needs to branch on — a string is the most
/// ergonomic interop format. The few variants that *do* carry data
/// (e.g. `DeviceNotFound`) embed it into the `Display` impl.
#[derive(Debug, thiserror::Error, uniffi::Error)]
#[uniffi(flat_error)]
#[allow(missing_docs)]
pub enum EngineError {
    #[error("device not found: {0}")]
    DeviceNotFound(String),

    #[error("invalid channels: {0:?}")]
    InvalidChannels(Vec<u32>),

    #[error("audio start failed: {0}")]
    AudioStartFailed(String),

    #[error("engine is already running; call stop_thru first")]
    AlreadyRunning,

    #[error("engine is not running")]
    NotRunning,

    #[error("invalid deck index {0} (valid: 0..{count})", count = dub_engine::DECK_COUNT)]
    InvalidDeckIndex(u64),

    /// File decoding failed (unsupported codec, corrupt file, IO error,
    /// or unsupported channel layout). M10.5.
    #[error("track decode failed: {0}")]
    TrackDecodeFailed(String),

    /// Sending a deck command to the audio thread failed because the
    /// SPSC command channel was full (audio thread not draining fast
    /// enough). M10.5.
    #[error("command channel full; retry")]
    CommandChannelFull,

    /// `load_track`/`play`/etc. called before `start_engine` /
    /// `start_thru` succeeded. M10.5.
    #[error("engine is not running; call start_engine first")]
    EngineNotRunning,
}

/// The Apple-side handle to the Dub audio engine.
///
/// Construct one with `DubEngine::new()` (UniFFI emits Swift's
/// `DubEngine()` for this). Methods are all `&self`-on-`Arc<Self>`,
/// so the same handle can be passed across threads and called from
/// the SwiftUI render loop without further synchronization on the
/// Swift side — the internal `Mutex` serialises mutating methods.
///
/// Lifecycle:
///
/// 1. `let engine = DubEngine()`
/// 2. `engine.listInputDevices()` → present the device picker
/// 3. `engine.startThru(deviceName, channels)` → begin capture
/// 4. Render loop polls `peaksLen` + `peaksExtend` for waveform data
/// 5. `engine.stopThru()` on quit (or rely on Swift dropping the
///    last reference; UniFFI's `Drop` impl invokes `stop_thru`
///    automatically)
#[derive(uniffi::Object)]
pub struct DubEngine {
    state: Mutex<EngineState>,
    /// Per-deck monotonic generation counter for the `PeakSource`
    /// slot. Bumps every time the slot is *assigned* a new source
    /// (Thru session start, `load_track` swap, etc.). Lives on
    /// `DubEngine` (not `RunningState`) so the value survives
    /// stop/start cycles — a Thru→Prep restart must trigger a
    /// renderer reset, but `RunningState` is dropped on stop so a
    /// counter inside it would reset to 0 and the renderer might
    /// miss the transition.
    ///
    /// The Swift renderer reads this via `peaks_generation(deck)`
    /// and `reset()`s its ring + cadence cache on every change.
    peak_generation_seq: [AtomicU64; 2],
}

/// Internal state machine for the engine.
///
/// `Stopped` is the freshly-constructed, post-`stop_thru`, and
/// post-failed-`start_thru` state. `Running` carries every handle
/// that needs to outlive the audio thread.
enum EngineState {
    Stopped,
    Running(Box<RunningState>),
}

/// Per-deck source of waveform peak data the renderer consumes.
///
/// Two variants for two playback modes:
///
/// * [`PeakSource::Live`] — Thru mode (M9): peaks are streamed off
///   the live audio-thread tap by a [`PeakStream`] analysis thread.
///   The data grows over time as the platter spins.
/// * [`PeakSource::File`] — File mode (M10.5): peaks were computed
///   synchronously off the fully-decoded [`Track`] at load time
///   ([`compute_offline_peaks`]). The data is fixed at the moment
///   of load — `peaks_len` reports `broadband.len()` and never
///   grows again.
///
/// The renderer's FFI methods ([`DubEngine::peaks_extend`],
/// [`DubEngine::peaks_len`], etc.) delegate through this enum so
/// Swift doesn't branch on mode — it just polls
/// `peaks_extend(deck, start_idx)` once per frame and gets the
/// authoritative chunks for whichever mode the deck is in.
enum PeakSource {
    /// Live Thru-mode capture. The `PeakStream`'s analysis thread
    /// reads from an audio-thread `ringbuf` tap and writes new
    /// chunks to a shared `PeakBuffer`.
    ///
    /// The `sample_rate` field is the analysis-side rate (= engine
    /// SR for Thru mode). Stored alongside the stream because
    /// `PeakStream` itself doesn't carry SR.
    Live {
        stream: PeakStream,
        sample_rate: u32,
    },
    /// Pre-computed File-mode peaks. The whole track's broadband +
    /// band peaks were decimated once during `load_track`.
    File(FilePeaks),
}

/// Offline-decoded peak buffer for a File-mode deck.
///
/// Mirrors the *exposed* surface of [`PeakStream`] (chunks, lengths,
/// per-chunk sample counts, sample rate) so the FFI accessors can
/// treat both variants uniformly. The underlying storage is just a
/// pair of `Vec`s — no analysis thread, no SPSC ring, no Drop work
/// at shutdown.
struct FilePeaks {
    broadband: Vec<PeakChunk>,
    bands: Vec<BandPeakChunk>,
    /// Per-hop onset-flux trail (M10.5l). Same cadence as `bands`
    /// (one entry per FFT hop) but a single `f32` per entry. The
    /// renderer reads this for transient-emphasising bloom +
    /// saturation in the waveform shader.
    onset: Vec<OnsetChunk>,
    /// Time-domain band-filtered peaks (M10.5p Stage 3). Same
    /// cadence as `broadband` (one entry per broadband chunk). v1
    /// populates only the LF band; MF / HF reserved. The DJ-
    /// landmarks shader palette reads this for the kick-prominence
    /// gate — see [`dub_peaks::filtered`] for the design rationale.
    filtered: Vec<FilteredPeakChunk>,
    /// Decoded-track sample rate. May differ from the engine SR
    /// (e.g. a 44.1 kHz MP3 played on a 48 kHz output). The renderer
    /// uses this to compute `chunk_duration_secs` (the time-axis
    /// scale factor), so a per-source rate is correct.
    sample_rate: u32,
    samples_per_broadband_chunk: u32,
    samples_per_band_chunk: u32,
    samples_per_onset_chunk: u32,
    /// Samples per filtered-peak chunk. Matches broadband cadence in
    /// v1 (the renderer indexes both streams 1:1).
    samples_per_filtered_chunk: u32,
    /// Beat grid (M10.5p), computed off-thread inside `load_track`
    /// via [`dub_bpm::analyze_beat_grid`]. Empty (confidence = 0)
    /// for tracks whose tempo couldn't be estimated.
    beat_grid: BeatGrid,
}

impl PeakSource {
    fn broadband_len(&self) -> usize {
        match self {
            PeakSource::Live { stream, .. } => stream.len(),
            PeakSource::File(f) => f.broadband.len(),
        }
    }

    fn band_len(&self) -> usize {
        match self {
            PeakSource::Live { stream, .. } => stream.band_len(),
            PeakSource::File(f) => f.bands.len(),
        }
    }

    fn sample_rate(&self) -> u32 {
        match self {
            PeakSource::Live { sample_rate, .. } => *sample_rate,
            PeakSource::File(f) => f.sample_rate,
        }
    }

    fn samples_per_broadband_chunk(&self) -> u32 {
        match self {
            PeakSource::Live { stream, .. } => {
                u32::try_from(stream.samples_per_chunk()).unwrap_or(u32::MAX)
            }
            PeakSource::File(f) => f.samples_per_broadband_chunk,
        }
    }

    fn samples_per_band_chunk(&self) -> Option<u32> {
        match self {
            PeakSource::Live { stream, .. } => stream
                .samples_per_band_chunk()
                .map(|n| u32::try_from(n).unwrap_or(u32::MAX)),
            PeakSource::File(f) => Some(f.samples_per_band_chunk),
        }
    }

    fn onset_len(&self) -> usize {
        match self {
            PeakSource::Live { stream, .. } => stream.onset_len(),
            PeakSource::File(f) => f.onset.len(),
        }
    }

    fn samples_per_onset_chunk(&self) -> Option<u32> {
        match self {
            PeakSource::Live { stream, .. } => stream
                .samples_per_onset_chunk()
                .map(|n| u32::try_from(n).unwrap_or(u32::MAX)),
            PeakSource::File(f) => Some(f.samples_per_onset_chunk),
        }
    }

    /// M10.5p Stage 3 — time-domain filtered-peak chunk count.
    ///
    /// Thru mode (`Live`) returns 0 in v1: the streaming
    /// `PeakStream` does not yet run a `FilteredDecimator` alongside
    /// its broadband/band/onset decimators (parked for a follow-up
    /// — Thru-mode users typically watch the turntable, not the
    /// screen, and the `djLandmarks` palette degrades to monochrome
    /// envelope without filtered data, which is acceptable). File
    /// mode returns the offline `compute_offline_peaks` result.
    fn filtered_len(&self) -> usize {
        match self {
            PeakSource::Live { .. } => 0,
            PeakSource::File(f) => f.filtered.len(),
        }
    }

    /// M10.5p Stage 3 — filtered-peak chunk cadence in samples.
    /// `None` for Thru mode (no filtered stream); `Some(64)` (=
    /// broadband cadence) for File mode.
    fn samples_per_filtered_chunk(&self) -> Option<u32> {
        match self {
            PeakSource::Live { .. } => None,
            PeakSource::File(f) => Some(f.samples_per_filtered_chunk),
        }
    }

    fn extend_broadband_from(&self, start: usize, out: &mut Vec<PeakChunk>) {
        match self {
            PeakSource::Live { stream, .. } => {
                let _new_end = stream.buffer().extend_chunks(start, out);
            }
            PeakSource::File(f) => {
                if start < f.broadband.len() {
                    out.extend_from_slice(&f.broadband[start..]);
                }
            }
        }
    }

    fn extend_band_from(&self, start: usize, out: &mut Vec<BandPeakChunk>) {
        match self {
            PeakSource::Live { stream, .. } => {
                let _new_end = stream.buffer().extend_band_chunks(start, out);
            }
            PeakSource::File(f) => {
                if start < f.bands.len() {
                    out.extend_from_slice(&f.bands[start..]);
                }
            }
        }
    }

    fn extend_onset_from(&self, start: usize, out: &mut Vec<OnsetChunk>) {
        match self {
            PeakSource::Live { stream, .. } => {
                let _new_end = stream.buffer().extend_onset_chunks(start, out);
            }
            PeakSource::File(f) => {
                if start < f.onset.len() {
                    out.extend_from_slice(&f.onset[start..]);
                }
            }
        }
    }

    /// M10.5p Stage 3. Thru mode is a no-op (no filtered stream
    /// emitted by `PeakStream` in v1); File mode copies from the
    /// offline-computed `filtered` Vec.
    fn extend_filtered_from(&self, start: usize, out: &mut Vec<FilteredPeakChunk>) {
        match self {
            PeakSource::Live { .. } => { /* no filtered stream in Thru v1 */ }
            PeakSource::File(f) => {
                if start < f.filtered.len() {
                    out.extend_from_slice(&f.filtered[start..]);
                }
            }
        }
    }
}

/// Active audio session. Field order matters for `Drop`:
///
/// 1. `peaks` is dropped first → each `PeakSource::Live` joins its
///    decimator thread cleanly. `PeakSource::File` drops `Vec`s, no
///    threading.
/// 2. `handle` is dropped second → the engine's main-thread proxy
///    releases its trash channels.
/// 3. `output` is dropped third → `AudioOutput::drop` stops the
///    CoreAudio output AudioUnit and reclaims the `Engine` it
///    owned.
/// 4. `input` is dropped last (when present) → no more samples flow.
struct RunningState {
    peaks: [Option<PeakSource>; 2],
    /// Per-deck loaded track (File mode). Held so [`DubEngine::track_info`]
    /// can read metadata after load. The engine's deck also holds a
    /// clone of this `Arc<Track>` — the audio thread reads samples
    /// through its own reference.
    file_tracks: [Option<Arc<Track>>; 2],
    /// Live engine command channel. Held purely so its `Drop` runs
    /// at the right point in the shutdown sequence.
    handle: EngineHandle,
    /// Live CoreAudio output AudioUnit. Held for `Drop`; renderer
    /// never touches it.
    #[allow(dead_code)]
    output: AudioOutput,
    /// Live CoreAudio input AudioUnit. `Some` in Thru mode (M9),
    /// `None` in output-only / File-only mode (M10.5).
    #[allow(dead_code)]
    input: Option<AudioInput>,
    /// Engine sample rate (= output device SR). May differ from a
    /// File-mode track's source SR — the engine resamples on render
    /// (PRD §4.4). File-mode peaks carry their own SR so the
    /// renderer's time-axis math is correct per-deck.
    sample_rate: u32,
}

impl DubEngine {
    /// Bump `peak_generation_seq[deck_idx]` by one with `Release`
    /// ordering. Internal helper called at every `PeakSource`
    /// assignment site so the Swift renderer can detect source
    /// swaps in a single shared signal regardless of which mutator
    /// (Thru start, two-deck Thru start, `load_track`) ran.
    ///
    /// Out-of-range indices are silently ignored — there are only
    /// ever two slots, and the caller has already validated the
    /// index via `deck_idx_to_usize` (or knows it statically). The
    /// silent no-op keeps every call site free of `unwrap`s on
    /// what is structurally a never-fail lookup.
    fn bump_peak_generation(&self, deck_idx: usize) {
        if let Some(a) = self.peak_generation_seq.get(deck_idx) {
            a.fetch_add(1, Ordering::Release);
        }
    }
}

#[uniffi::export]
impl DubEngine {
    /// Construct a fresh engine handle. The audio system is not
    /// touched yet — `start_thru` does that.
    #[uniffi::constructor]
    #[must_use]
    pub fn new() -> Arc<Self> {
        Arc::new(Self {
            state: Mutex::new(EngineState::Stopped),
            peak_generation_seq: [AtomicU64::new(0), AtomicU64::new(0)],
        })
    }

    /// Enumerate CoreAudio input devices. Returns just their names;
    /// the Swift picker passes one of these strings back to
    /// [`start_thru`].
    ///
    /// Off-RT; safe to call at any time. Returns an empty list if
    /// CoreAudio enumeration fails for any reason (logged via
    /// `eprintln!`; we don't surface enumeration errors as
    /// `EngineError` because that would force every consumer to
    /// branch on a near-impossible failure).
    #[must_use]
    pub fn list_input_devices(&self) -> Vec<String> {
        match dub_audio::list_input_devices() {
            Ok(devs) => devs.into_iter().map(|d| d.name).collect(),
            Err(e) => {
                eprintln!("dub-ffi: list_input_devices failed: {e}");
                Vec::new()
            }
        }
    }

    /// Return `true` iff at least one external audio interface
    /// with input streams is currently attached to the system.
    ///
    /// Used by the Apple shell's auto-detect on launch (PRD §3.1)
    /// to decide between Performance / Timecode mode (external
    /// interface present) and Track Preparation / output-only
    /// mode (none present). Critically, this probe does **not**
    /// trip macOS's microphone-permission prompt: it queries
    /// transport-type metadata and input-scope availability only,
    /// without ever touching device names, channel counts, or AU
    /// instantiation. The mic prompt only fires later when (and
    /// if) the user actually starts a Timecode session against an
    /// external interface.
    ///
    /// See [`dub_audio::has_external_audio_interface`] for the
    /// exhaustive definition of "external" (USB / Thunderbolt /
    /// FireWire / PCI / AVB; Bluetooth / HDMI / AirPlay /
    /// Continuity Capture are not external for this purpose).
    #[must_use]
    pub fn has_external_audio_interface(&self) -> bool {
        dub_audio::has_external_audio_interface()
    }

    /// Begin a Thru session: open the input device by name on the
    /// given 1-based channel pair, start a default-stereo output AU,
    /// and attach a `ThruSource` + `PeakStream` on deck 0.
    ///
    /// `channels` is a pair of 1-based CoreAudio input-channel
    /// indices (e.g. `[3, 4]` for the canonical SL3 timecode pair).
    ///
    /// # Errors
    ///
    /// * [`EngineError::AlreadyRunning`] if the engine is already in
    ///   `Running` state. Call `stop_thru` first.
    /// * [`EngineError::InvalidChannels`] if `channels.len() != 2`
    ///   or any channel index is `0` (the FFI uses 1-based indices
    ///   to stay consistent with the CLI).
    /// * [`EngineError::DeviceNotFound`] if no input device matches
    ///   `device_name`.
    /// * [`EngineError::AudioStartFailed`] for any other CoreAudio
    ///   open / attach failure.
    pub fn start_thru(&self, device_name: String, channels: Vec<u32>) -> Result<(), EngineError> {
        let mut state = lock_state(&self.state);
        if matches!(*state, EngineState::Running(_)) {
            return Err(EngineError::AlreadyRunning);
        }

        if channels.len() != 2 || channels.contains(&0) {
            return Err(EngineError::InvalidChannels(channels));
        }

        let running = start_thru_inner(&device_name, &channels, None)?;
        *state = EngineState::Running(Box::new(running));
        self.bump_peak_generation(0);
        Ok(())
    }

    /// Begin a **two-deck** Thru session: open the input device on
    /// the combined 4-channel set (deck A pair + deck B pair), demux
    /// in the IOProc into two stereo SPSC rings, and attach a
    /// `ThruSource` + `PeakStream` on both deck 0 and deck 1.
    ///
    /// The renderer can then poll `peaks_len(0)` / `peaks_len(1)`
    /// independently and show one waveform per deck.
    ///
    /// `channels_a` and `channels_b` are each 1-based pairs (e.g.
    /// `channels_a = [3, 4]`, `channels_b = [5, 6]` for the canonical
    /// SL3 two-deck layout). Channels must not overlap.
    ///
    /// # Errors
    ///
    /// Same as [`start_thru`] for the deck A pair, plus:
    /// * [`EngineError::InvalidChannels`] if `channels_b.len() != 2`,
    ///   any index is `0`, or the A/B pairs share a channel.
    pub fn start_thru_two_deck(
        &self,
        device_name: String,
        channels_a: Vec<u32>,
        channels_b: Vec<u32>,
    ) -> Result<(), EngineError> {
        let mut state = lock_state(&self.state);
        if matches!(*state, EngineState::Running(_)) {
            return Err(EngineError::AlreadyRunning);
        }

        if channels_a.len() != 2 || channels_a.contains(&0) {
            return Err(EngineError::InvalidChannels(channels_a));
        }
        if channels_b.len() != 2 || channels_b.contains(&0) {
            return Err(EngineError::InvalidChannels(channels_b));
        }
        // No channel may appear in both pairs.
        if channels_a.iter().any(|c| channels_b.contains(c)) {
            let mut combined = channels_a;
            combined.extend(channels_b);
            return Err(EngineError::InvalidChannels(combined));
        }

        let running = start_thru_inner(&device_name, &channels_a, Some(&channels_b))?;
        *state = EngineState::Running(Box::new(running));
        self.bump_peak_generation(0);
        self.bump_peak_generation(1);
        Ok(())
    }

    /// Tear down the Thru session. Idempotent — calling `stop_thru`
    /// on an already-stopped engine is a no-op (no error).
    pub fn stop_thru(&self) {
        let mut state = lock_state(&self.state);
        // Move out the running state so its drop order runs while
        // the mutex is held. Dropping the inner state runs the
        // shutdown sequence documented on `RunningState`.
        let prev = std::mem::replace(&mut *state, EngineState::Stopped);
        drop(prev);
    }

    /// Alias of [`Self::stop_thru`] for parity with the M10.5
    /// `start_engine` naming. Same idempotent semantics: tears the
    /// session down regardless of whether it was started in Thru,
    /// two-deck-Thru, or output-only mode.
    pub fn stop_engine(&self) {
        self.stop_thru();
    }

    /// Start an **output-only** engine session (M10.5).
    ///
    /// No input device is opened — the engine renders whatever the
    /// decks output (File mode) and nothing else. Use this when a
    /// timecode interface is not available and the DJ wants to
    /// drag-and-drop tracks onto decks for casual playback / track
    /// preparation (PRD §6.1.3).
    ///
    /// `output_channels` is the number of physical output channels
    /// to open the AU with. Pass `2` for stereo (built-in speakers,
    /// headphones); pass `4` to mirror the canonical SL3 layout
    /// (deck A → ch 1+2, deck B → ch 3+4) so a follow-up
    /// `start_thru_two_deck` call from the same UI gives consistent
    /// physical routing. Output device is the system default; choose
    /// via Audio MIDI Setup (PRD §10).
    ///
    /// After success, the deck count is `dub_engine::DECK_COUNT` (= 2);
    /// each deck starts empty (no peaks, no track). Call
    /// [`Self::load_track`] to populate.
    ///
    /// # Errors
    ///
    /// * [`EngineError::AlreadyRunning`] if a session is already
    ///   active.
    /// * [`EngineError::InvalidChannels`] if `output_channels < 2`.
    /// * [`EngineError::AudioStartFailed`] for any CoreAudio
    ///   open/start failure.
    pub fn start_engine(&self, output_channels: u32) -> Result<(), EngineError> {
        let mut state = lock_state(&self.state);
        if matches!(*state, EngineState::Running(_)) {
            return Err(EngineError::AlreadyRunning);
        }
        if output_channels < 2 {
            return Err(EngineError::InvalidChannels(vec![output_channels]));
        }

        let running = start_engine_inner(output_channels)?;
        *state = EngineState::Running(Box::new(running));
        Ok(())
    }

    /// Load a track on the given deck (M10.5).
    ///
    /// Decodes the file at `path` via
    /// [`dub_io::Track::load_from_path`], computes the whole-track
    /// peaks via [`compute_offline_peaks`], stores them in the
    /// per-deck [`PeakSource::File`], and sends `Command::DeckLoad`
    /// to the audio thread. Position is reset to `0.0` and the
    /// deck starts in the paused state — the caller is expected to
    /// follow up with [`Self::play`].
    ///
    /// **Locking discipline (M10.5d).** This call is split into
    /// three phases:
    ///
    /// 1. **Quick check** under the engine-state mutex: validate
    ///    that `start_engine` has been called. Mutex is released
    ///    before the slow work begins.
    /// 2. **Slow decode + peaks compute, mutex-free.** A typical
    ///    4-minute MP3 spends ~50 ms in symphonia and another
    ///    ~20 ms in `compute_offline_peaks`; both are heap-allocating
    ///    and would block every concurrent `position()` /
    ///    `peaks_extend()` / `track_info()` call (the 30 Hz UI poll)
    ///    if held under the mutex. With the mutex released, the
    ///    rest of the API stays responsive throughout the load.
    ///    The Apple shell additionally dispatches this whole call
    ///    onto a `Task.detached`, so it doesn't block the SwiftUI
    ///    main actor either.
    /// 3. **Quick swap** under the engine-state mutex: install the
    ///    new `Arc<Track>` + `FilePeaks` and bump
    ///    `peak_generation_seq` so the renderer resets to the new
    ///    peaks on the next frame.
    ///
    /// The check between phases 1 and 3 is repeated — the engine
    /// can theoretically be stopped while decode is in flight, in
    /// which case phase 3 returns [`EngineError::EngineNotRunning`]
    /// and the decoded `Arc<Track>` + peak vectors are dropped on
    /// the caller's thread (off-RT, harmless). Two concurrent
    /// loads on the same deck race for phase 3: whichever lands
    /// last wins, and the earlier one's `Arc<Track>` is then
    /// displaced via the engine's existing trash-channel path on
    /// the next `Command::DeckLoad` swap.
    ///
    /// # Errors
    ///
    /// * [`EngineError::EngineNotRunning`] if `start_engine` /
    ///   `start_thru` hasn't been called (checked at phases 1 and 3).
    /// * [`EngineError::InvalidDeckIndex`] if `deck_idx >=
    ///   DECK_COUNT`.
    /// * [`EngineError::TrackDecodeFailed`] for any IO / codec /
    ///   layout / empty-decode failure.
    /// * [`EngineError::CommandChannelFull`] if the audio thread is
    ///   not draining commands (implausible in normal operation —
    ///   the channel is sized for hundreds of pending commands).
    pub fn load_track(&self, deck_idx: u64, path: String) -> Result<(), EngineError> {
        let idx = deck_idx_to_usize(deck_idx)?;

        // Phase 1: quick mutex-protected check that the engine is
        // running. Mutex drops at the end of this scope so the
        // expensive decode below doesn't starve the 30 Hz poll.
        {
            let state = lock_state(&self.state);
            if !matches!(*state, EngineState::Running(_)) {
                return Err(EngineError::EngineNotRunning);
            }
        }

        // Phase 2: slow work, mutex-free. Both `Track::load_from_path`
        // (symphonia decode + Vec<f32> allocation) and
        // `compute_offline_peaks` (broadband + band ring fills) are
        // heap-heavy; running them under the engine mutex would
        // block every UI poll for the duration of the load.
        let track = Track::load_from_path(&path)
            .map_err(|e| EngineError::TrackDecodeFailed(format!("{path}: {e}")))?;
        let track = Arc::new(track);

        let OfflinePeaks {
            broadband,
            bands,
            onset,
            filtered,
            sample_rate,
            samples_per_broadband_chunk,
            samples_per_band_chunk,
            samples_per_onset_chunk,
            samples_per_filtered_chunk,
        } = compute_offline_peaks(track.samples(), track.sample_rate(), track.channels())
            .map_err(|e| EngineError::TrackDecodeFailed(format!("peaks: {e}")))?;

        // Beat grid (M10.5p) — *temporarily disabled* alongside the
        // Stage 1 tick overlay (parked for a dedicated future
        // "beat-grid v2" milestone — tempo-drift handling, manual
        // phase correction, downbeat detection, all the sub-tasks
        // a real grid feature needs). The original M10.5p Stage 1
        // pass added ~100 ms per `load_track` (BPM + ODF + phase
        // search on the whole sample buffer) for a feature that's
        // not currently rendered. Skipping it here keeps loads
        // snappy. The `BeatGrid` FFI Record + the
        // `DubEngine::beat_grid` accessor stay in place so the
        // future grid milestone can wire the computation back in
        // without an FFI version bump.
        //
        // Re-enable path: replace the line below with
        //
        //     let beat_grid = match dub_bpm::analyze_beat_grid(
        //         track.samples(),
        //         track.sample_rate(),
        //         track.channels(),
        //     ) {
        //         Ok(g) => BeatGrid::from_core(g),
        //         Err(_) => BeatGrid::empty(),
        //     };
        //
        // and re-add the `analyze_beat_grid` import at the top.
        // `dub_bpm::analyze_beat_grid` and its tests stay live
        // (see `dub-bpm/src/beats.rs`) so the contract doesn't
        // bit-rot in the meantime.
        let beat_grid = BeatGrid::empty();

        // Phase 3: quick mutex-protected swap. Re-validate that the
        // engine is still running — it may have been stopped while
        // we were decoding, in which case we drop the freshly-built
        // Arc<Track> + peaks here (off-RT, harmless).
        let mut state = lock_state(&self.state);
        let EngineState::Running(running) = &mut *state else {
            return Err(EngineError::EngineNotRunning);
        };

        running
            .handle
            .deck(idx)
            .load(track.clone())
            .map_err(|(e, _arc)| match e {
                dub_engine::CommandError::ChannelFull => EngineError::CommandChannelFull,
                dub_engine::CommandError::InvalidDeck { idx, .. } => {
                    EngineError::InvalidDeckIndex(u64::from(idx))
                }
            })?;

        running.file_tracks[idx] = Some(track);
        running.peaks[idx] = Some(PeakSource::File(FilePeaks {
            broadband,
            bands,
            onset,
            filtered,
            sample_rate,
            samples_per_broadband_chunk: u32::try_from(samples_per_broadband_chunk)
                .unwrap_or(u32::MAX),
            samples_per_band_chunk: u32::try_from(samples_per_band_chunk).unwrap_or(u32::MAX),
            samples_per_onset_chunk: u32::try_from(samples_per_onset_chunk).unwrap_or(u32::MAX),
            samples_per_filtered_chunk: u32::try_from(samples_per_filtered_chunk)
                .unwrap_or(u32::MAX),
            beat_grid,
        }));
        // The generation atomic lives on `DubEngine` directly, not
        // inside `Mutex<EngineState>`, so this access doesn't
        // re-acquire the state mutex (which would deadlock us). We
        // bump it while still holding the guard so a renderer poll
        // that sees the new peaks also sees the new generation —
        // no torn-read window.
        if let Some(a) = self.peak_generation_seq.get(idx) {
            a.fetch_add(1, Ordering::Release);
        }

        Ok(())
    }

    /// Start playback on the given deck (M10.5).
    ///
    /// In File mode, advances the playhead at unity rate from its
    /// current position. In Thru mode, this is a no-op at the engine
    /// level (the timecode carrier drives the rate) but sent
    /// anyway so the deck's `is_playing` flag is consistent with the
    /// UI. Idempotent: playing an already-playing deck is harmless.
    ///
    /// # Errors
    ///
    /// See [`Self::load_track`] for the error model; same variants
    /// apply.
    pub fn play(&self, deck_idx: u64) -> Result<(), EngineError> {
        let idx = deck_idx_to_usize(deck_idx)?;
        let mut state = lock_state(&self.state);
        let EngineState::Running(running) = &mut *state else {
            return Err(EngineError::EngineNotRunning);
        };
        running.handle.deck(idx).play().map_err(map_command_error)
    }

    /// Pause playback on the given deck (M10.5).
    ///
    /// File mode freezes the playhead at its current position.
    /// Position can be resumed with [`Self::play`] or jumped with
    /// [`Self::seek`].
    ///
    /// # Errors
    ///
    /// Same as [`Self::play`].
    pub fn pause(&self, deck_idx: u64) -> Result<(), EngineError> {
        let idx = deck_idx_to_usize(deck_idx)?;
        let mut state = lock_state(&self.state);
        let EngineState::Running(running) = &mut *state else {
            return Err(EngineError::EngineNotRunning);
        };
        running.handle.deck(idx).pause().map_err(map_command_error)
    }

    /// Set deck `deck_idx`'s **musical** playback rate (M10.5s).
    ///
    /// `1.0` = normal forward at the track's native pitch. `2.0` =
    /// double-speed forward (octave up). `-1.0` = reverse at unity
    /// (rewinding at native speed). `0.0` = playhead frozen (deck
    /// still consumes audio frames but produces a constant sample —
    /// see the mouse-scratch UI for the gate that pauses the deck
    /// on prolonged near-zero rates so the user doesn't hear a DC
    /// thump).
    ///
    /// **Sample-rate conversion is done here.** The user supplies a
    /// rate in "audio seconds per real second" (= musical speed);
    /// the engine internally drives source frames per output frame.
    /// We multiply by `track_sr / engine_sr` so callers don't have
    /// to know about engine SR. When no track is loaded we still
    /// send the command — the engine treats it as a no-op so the UI
    /// doesn't have to special-case empty decks.
    ///
    /// **Timecode-mode interaction.** Without Panic Play the
    /// timecode driver overwrites the rate every block, so this
    /// call is effectively a one-block hint that disappears
    /// immediately. To drive rate from outside the timecode pipeline
    /// (e.g. mouse-scratch) callers must engage [`Self::panic_play`]
    /// first; that decouples the deck from the platter and lets
    /// `set_deck_rate` stick. The scratch state machine in the
    /// Apple shell does exactly this.
    ///
    /// Cheap: one SPSC channel push to the audio thread.
    ///
    /// # Errors
    ///
    /// Same as [`Self::play`].
    pub fn set_deck_rate(&self, deck_idx: u64, rate: f64) -> Result<(), EngineError> {
        let idx = deck_idx_to_usize(deck_idx)?;
        let mut state = lock_state(&self.state);
        let EngineState::Running(running) = &mut *state else {
            return Err(EngineError::EngineNotRunning);
        };

        // SR conversion: convert musical rate (audio_secs / real_sec)
        // into source frames per output frame. When the track SR
        // isn't yet known we send the musical rate as-is; the deck's
        // own resampler will handle the engine-side rate either way.
        let engine_rate = match running.file_tracks[idx].as_ref() {
            Some(track) => {
                let track_sr = f64::from(track.sample_rate());
                let engine_sr = f64::from(running.sample_rate);
                if engine_sr > 0.0 {
                    rate * track_sr / engine_sr
                } else {
                    rate
                }
            }
            None => rate,
        };

        running
            .handle
            .deck(idx)
            .set_rate(engine_rate)
            .map_err(map_command_error)
    }

    /// M10.6b Panic-Play engage (PRD §6.1.2).
    ///
    /// Tells the engine to ignore the deck's timecode input until
    /// either a clean LFSR re-lock auto-cancels, or the UI sends
    /// [`Self::cancel_panic_play`]. While engaged the deck plays at
    /// its last-known good velocity (read from
    /// `LiftPolicy::last_locked_rate` if a timecode input is
    /// attached, falling back to the deck's commanded rate). The
    /// held rate is normalised to a positive forward value per the
    /// PRD: a panicked backspin will continue forward, not keep
    /// rewinding.
    ///
    /// Idempotent w.r.t. the engine: calling `panic_play` on a deck
    /// already in panic state simply re-captures the held rate
    /// (useful if the user re-triggers panic after a slight pitch
    /// adjustment). The UI's "click panic glyph" pattern is a
    /// toggle layered on top of this FFI surface — when the deck is
    /// already in panic the UI should send
    /// [`Self::cancel_panic_play`] instead.
    ///
    /// # Errors
    ///
    /// Same as [`Self::play`].
    pub fn panic_play(&self, deck_idx: u64) -> Result<(), EngineError> {
        let idx = deck_idx_to_usize(deck_idx)?;
        let mut state = lock_state(&self.state);
        let EngineState::Running(running) = &mut *state else {
            return Err(EngineError::EngineNotRunning);
        };
        running
            .handle
            .deck(idx)
            .panic_play()
            .map_err(map_command_error)
    }

    /// Panic-Play manual cancel (PRD §6.1.2, M10.6d UI redesign).
    ///
    /// Clears the engine's panic state and hands deck transport
    /// authority back to the timecode driver. Crucially, this **does
    /// not** pause the deck — if a clean carrier is present, the
    /// next render block re-locks on it and the deck stays audible
    /// (Serato INT→ABS path). If the carrier is silent, the
    /// driver's existing `DropoutHoldRate` arm pauses the deck on
    /// the next block, yielding the pre-M10.6c "pause on held
    /// position" outcome without racing a manual `set_playing(false)`
    /// against the next Locked sample. Idempotent — a cancel on a
    /// non-engaged deck is a no-op.
    ///
    /// # Errors
    ///
    /// Same as [`Self::play`].
    pub fn cancel_panic_play(&self, deck_idx: u64) -> Result<(), EngineError> {
        let idx = deck_idx_to_usize(deck_idx)?;
        let mut state = lock_state(&self.state);
        let EngineState::Running(running) = &mut *state else {
            return Err(EngineError::EngineNotRunning);
        };
        running
            .handle
            .deck(idx)
            .cancel_panic_play()
            .map_err(map_command_error)
    }

    /// Seek to the given time position on the deck (M10.5).
    ///
    /// `position_secs` is the wall-clock offset from track start.
    /// Negative values and values past the end are allowed — the
    /// engine renders silence and keeps advancing, mirroring a real
    /// record being lifted off the platter. The actual frame
    /// position is `position_secs × track.sample_rate()`; rounding
    /// is to the nearest frame.
    ///
    /// # Errors
    ///
    /// Same as [`Self::play`].
    pub fn seek(&self, deck_idx: u64, position_secs: f64) -> Result<(), EngineError> {
        let idx = deck_idx_to_usize(deck_idx)?;
        let mut state = lock_state(&self.state);
        let EngineState::Running(running) = &mut *state else {
            return Err(EngineError::EngineNotRunning);
        };

        // Convert seconds → track frames using the loaded track's
        // SR (not the engine SR). If no track is loaded, we still
        // send the command (engine treats it as out-of-range silence)
        // so the UI doesn't have to special-case empty decks.
        let position_frames = match running.file_tracks[idx].as_ref() {
            #[allow(clippy::cast_precision_loss)]
            Some(track) => position_secs * f64::from(track.sample_rate()),
            None => position_secs,
        };

        running
            .handle
            .deck(idx)
            .seek(position_frames)
            .map_err(map_command_error)
    }

    /// Read the current playhead position on the deck (M10.5).
    ///
    /// Returns a [`PositionInfo`] with elapsed seconds, remaining
    /// seconds, total duration, and the deck's transport state.
    /// All fields are zero when the engine is stopped or the deck
    /// is empty.
    ///
    /// Cheap: a few `Relaxed` atomic loads. Safe to call from a
    /// 30 Hz / 60 Hz UI loop without rate-limiting.
    #[must_use]
    pub fn position(&self, deck_idx: u64) -> PositionInfo {
        let idx = match deck_idx_to_usize(deck_idx) {
            Ok(idx) => idx,
            Err(_) => return PositionInfo::EMPTY,
        };
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return PositionInfo::EMPTY;
        };
        let Some(snap) = running.handle.deck_state(idx) else {
            return PositionInfo::EMPTY;
        };
        let Some(track) = running.file_tracks[idx].as_ref() else {
            return PositionInfo {
                has_track: false,
                is_playing: snap.is_playing,
                is_panic_play: snap.is_panic_play,
                ..PositionInfo::EMPTY
            };
        };
        let sr = f64::from(track.sample_rate());
        let duration_secs = if sr > 0.0 {
            #[allow(clippy::cast_precision_loss)]
            let total_frames = track.frames() as f64;
            total_frames / sr
        } else {
            0.0
        };
        let playhead_secs_unclamped = if sr > 0.0 {
            snap.position_frames / sr
        } else {
            0.0
        };
        let elapsed_secs = playhead_secs_unclamped.max(0.0).min(duration_secs);
        let remaining_secs = (duration_secs - elapsed_secs).max(0.0);
        PositionInfo {
            elapsed_secs,
            playhead_secs_unclamped,
            remaining_secs,
            duration_secs,
            is_playing: snap.is_playing,
            at_end: snap.at_end,
            has_track: true,
            is_panic_play: snap.is_panic_play,
        }
    }

    /// Read metadata for the currently-loaded File-mode track on the
    /// deck (M10.5).
    ///
    /// Returns `None` if no track is loaded or the engine is stopped.
    ///
    /// Title / artist are best-effort placeholders today (the file
    /// stem) — M11 library import will populate them from
    /// Serato/Traktor/rekordbox tags or symphonia metadata.
    #[must_use]
    pub fn track_info(&self, deck_idx: u64) -> Option<TrackInfo> {
        let idx = deck_idx_to_usize(deck_idx).ok()?;
        let state = lock_state(&self.state);
        let running = state.as_running()?;
        let track = running.file_tracks[idx].as_ref()?;
        Some(TrackInfo {
            title: track.title().unwrap_or_default().to_string(),
            artist: track.artist().unwrap_or_default().to_string(),
            duration_secs: track.duration_seconds(),
            sample_rate: track.sample_rate(),
            channels: u32::from(track.channels()),
            bpm: track.bpm(),
        })
    }

    /// Per-deck beat grid (M10.5p). Returns the cached
    /// [`dub_bpm::analyze_beat_grid`] result from the most recent
    /// `load_track` call.
    ///
    /// Returns an empty grid (`confidence == 0.0`, `beats: []`)
    /// when:
    ///
    /// * the engine isn't running
    /// * `deck_idx` is out of range
    /// * the deck has no track loaded
    /// * the deck holds a live (Thru) source — Thru-mode beat
    ///   tracking is M11.5 scope (the streaming `BpmTracker` only
    ///   tracks tempo today, no phase)
    /// * the loaded track was too short for tempo analysis or its
    ///   tempo couldn't be estimated
    ///
    /// Renderers should redraw their tick overlay whenever
    /// [`Self::peaks_generation`] for the same deck changes.
    #[must_use]
    pub fn beat_grid(&self, deck_idx: u64) -> BeatGrid {
        let Ok(idx) = deck_idx_to_usize(deck_idx) else {
            return BeatGrid::empty();
        };
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return BeatGrid::empty();
        };
        match running.peaks[idx].as_ref() {
            Some(PeakSource::File(f)) => f.beat_grid.clone(),
            _ => BeatGrid::empty(),
        }
    }

    /// Monotonic generation counter for the deck's [`PeakSource`].
    /// Bumps every time the slot is *assigned* (Thru session start,
    /// `load_track` swap, engine restart, etc.). Survives stop/
    /// start cycles — the counter lives on `DubEngine` itself, not
    /// inside `RunningState`. Returns the last observed value (or
    /// `0` if the engine has never been started) when `deck_idx`
    /// is out of range.
    ///
    /// The Swift renderer compares this against its cached value
    /// each frame; a mismatch means the source was replaced, and the
    /// renderer must `reset()` its ring buffer + cadence caches
    /// before re-ingesting from `start_idx = 0`. Without this signal
    /// the renderer keeps rendering stale chunks from the previous
    /// source after a Thru → File swap, because `peaks_len` may
    /// regress (a 3-minute MP3's broadband peak count is smaller
    /// than the Thru ring's running length after a few minutes of
    /// capture) and the length-monotonicity heuristic silently no-
    /// ops the ingest path forever.
    #[must_use]
    pub fn peaks_generation(&self, deck_idx: u64) -> u64 {
        let Ok(idx) = deck_idx_to_usize(deck_idx) else {
            return 0;
        };
        self.peak_generation_seq
            .get(idx)
            .map_or(0, |a| a.load(Ordering::Acquire))
    }

    /// Number of broadband [`PeakChunk`]s captured so far on `deck_idx`.
    ///
    /// Returns `0` if the engine is stopped or the deck has no
    /// peaks stream. Cheap (lock-free `AtomicUsize` load after the
    /// state mutex acquire).
    #[must_use]
    pub fn peaks_len(&self, deck_idx: u64) -> u64 {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return 0;
        };
        let Some(source) = peak_source_for(running, deck_idx) else {
            return 0;
        };
        source.broadband_len() as u64
    }

    /// Wall-clock duration of one [`PeakChunk`] on `deck_idx`, in
    /// seconds. `samples_per_chunk / sample_rate`. Returns `0.0`
    /// when stopped / unknown deck — Swift uses the result as a
    /// time-axis scale factor, and a zero scale produces a sane
    /// empty waveform rather than NaN.
    ///
    /// Mode-aware: in Thru mode the rate is the engine SR (= input
    /// device SR); in File mode the rate is the loaded track's SR
    /// (may differ from output device SR — the engine resamples on
    /// render, but peaks are at source-rate cadence).
    #[must_use]
    pub fn peaks_chunk_duration_secs(&self, deck_idx: u64) -> f64 {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return 0.0;
        };
        let Some(source) = peak_source_for(running, deck_idx) else {
            return 0.0;
        };
        let sr = source.sample_rate();
        if sr == 0 {
            return 0.0;
        }
        f64::from(source.samples_per_broadband_chunk()) / f64::from(sr)
    }

    /// Fetch new [`PeakChunk`]s captured since `start_idx`,
    /// serialised as a raw byte buffer suitable for direct upload
    /// to a `MTLBuffer`. The Swift side reinterprets each 12-byte
    /// stride as a `(f32 min, f32 max, f32 rms)` triple.
    ///
    /// Caller cache-discipline: after each call, Swift advances
    /// its `start_idx` by `bytes.count / 12`. `peaks_len` is the
    /// authoritative total; this method's return covers
    /// `[start_idx, peaks_len)`.
    ///
    /// Returns an empty `Vec` when the engine is stopped, the deck
    /// has no peaks source, or `start_idx >= len()`.
    #[must_use]
    pub fn peaks_extend(&self, deck_idx: u64, start_idx: u64) -> Vec<u8> {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return Vec::new();
        };
        let Some(source) = peak_source_for(running, deck_idx) else {
            return Vec::new();
        };
        let mut chunks: Vec<PeakChunk> = Vec::new();
        source.extend_broadband_from(usize_from_u64(start_idx), &mut chunks);
        peak_chunks_to_bytes(&chunks)
    }

    /// Number of [`BandPeakChunk`]s captured so far on `deck_idx`.
    /// Returns `0` if band capture is disabled or the engine is
    /// stopped.
    #[must_use]
    pub fn band_peaks_len(&self, deck_idx: u64) -> u64 {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return 0;
        };
        let Some(source) = peak_source_for(running, deck_idx) else {
            return 0;
        };
        source.band_len() as u64
    }

    /// Wall-clock duration of one [`BandPeakChunk`] on `deck_idx`,
    /// in seconds. Equals `BAND_SAMPLES_PER_CHUNK / sample_rate`.
    /// Returns `0.0` if band capture is disabled, the engine is
    /// stopped, or the deck has no stream.
    #[must_use]
    pub fn band_peaks_chunk_duration_secs(&self, deck_idx: u64) -> f64 {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return 0.0;
        };
        let Some(source) = peak_source_for(running, deck_idx) else {
            return 0.0;
        };
        let Some(spbc) = source.samples_per_band_chunk() else {
            return 0.0;
        };
        let sr = source.sample_rate();
        if sr == 0 {
            return 0.0;
        }
        f64::from(spbc) / f64::from(sr)
    }

    /// Current audio sample rate the engine is running at, in Hz.
    /// Returns `0` when the engine is stopped.
    ///
    /// M10.1 renderers use this to derive `samplesPerChunk` from
    /// `peaks_chunk_duration_secs` — `dur × sample_rate` is the
    /// exact integer cadence the GPU shader needs to map between
    /// the broadband and band rings.
    #[must_use]
    pub fn sample_rate(&self) -> u32 {
        let state = lock_state(&self.state);
        state.as_running().map_or(0, |r| r.sample_rate)
    }

    /// Fetch new [`BandPeakChunk`]s captured since `start_idx`,
    /// serialised as bytes (8 × `f32` per chunk = 32 bytes stride).
    /// Used by the M10.1 multi-colour shader.
    ///
    /// Returns an empty `Vec` when band capture is disabled, the
    /// engine is stopped, or `start_idx >= band_len()`.
    #[must_use]
    pub fn band_peaks_extend(&self, deck_idx: u64, start_idx: u64) -> Vec<u8> {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return Vec::new();
        };
        let Some(source) = peak_source_for(running, deck_idx) else {
            return Vec::new();
        };
        let mut chunks: Vec<BandPeakChunk> = Vec::new();
        source.extend_band_from(usize_from_u64(start_idx), &mut chunks);
        band_peak_chunks_to_bytes(&chunks)
    }

    /// Number of [`OnsetChunk`]s captured so far on `deck_idx`
    /// (M10.5l). Returns `0` if onset capture is disabled or the
    /// engine is stopped.
    #[must_use]
    pub fn onset_peaks_len(&self, deck_idx: u64) -> u64 {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return 0;
        };
        let Some(source) = peak_source_for(running, deck_idx) else {
            return 0;
        };
        source.onset_len() as u64
    }

    /// Wall-clock duration of one [`OnsetChunk`] on `deck_idx`, in
    /// seconds. Equals `samples_per_onset_chunk / sample_rate`,
    /// which is identical to the band-chunk cadence (one entry per
    /// FFT hop).
    ///
    /// Returns `0.0` if onset capture is disabled, the engine is
    /// stopped, or the deck has no stream.
    #[must_use]
    pub fn onset_peaks_chunk_duration_secs(&self, deck_idx: u64) -> f64 {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return 0.0;
        };
        let Some(source) = peak_source_for(running, deck_idx) else {
            return 0.0;
        };
        let Some(spoc) = source.samples_per_onset_chunk() else {
            return 0.0;
        };
        let sr = source.sample_rate();
        if sr == 0 {
            return 0.0;
        }
        f64::from(spoc) / f64::from(sr)
    }

    /// Fetch new [`OnsetChunk`]s captured since `start_idx`,
    /// serialised as bytes (1 × `f32` per chunk = 4 bytes stride).
    /// Used by the M10.5l transient-emphasising waveform shader.
    ///
    /// Returns an empty `Vec` when onset capture is disabled, the
    /// engine is stopped, or `start_idx >= onset_len()`.
    #[must_use]
    pub fn onset_peaks_extend(&self, deck_idx: u64, start_idx: u64) -> Vec<u8> {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return Vec::new();
        };
        let Some(source) = peak_source_for(running, deck_idx) else {
            return Vec::new();
        };
        let mut chunks: Vec<OnsetChunk> = Vec::new();
        source.extend_onset_from(usize_from_u64(start_idx), &mut chunks);
        onset_chunks_to_bytes(&chunks)
    }

    /// M10.5p Stage 3 — number of [`FilteredPeakChunk`]s available on
    /// `deck_idx`. Returns `0` for Thru-mode decks (no filtered
    /// stream emitted in v1) and for stopped engines.
    #[must_use]
    pub fn filtered_peaks_len(&self, deck_idx: u64) -> u64 {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return 0;
        };
        let Some(source) = peak_source_for(running, deck_idx) else {
            return 0;
        };
        source.filtered_len() as u64
    }

    /// M10.5p Stage 3 — wall-clock duration of one
    /// [`FilteredPeakChunk`] on `deck_idx`, in seconds. Equal to the
    /// broadband-chunk duration (filtered cadence matches broadband
    /// 1:1 by design). Returns `0.0` for Thru-mode decks and
    /// stopped engines.
    #[must_use]
    pub fn filtered_peaks_chunk_duration_secs(&self, deck_idx: u64) -> f64 {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return 0.0;
        };
        let Some(source) = peak_source_for(running, deck_idx) else {
            return 0.0;
        };
        let Some(spfc) = source.samples_per_filtered_chunk() else {
            return 0.0;
        };
        let sr = source.sample_rate();
        if sr == 0 {
            return 0.0;
        }
        f64::from(spfc) / f64::from(sr)
    }

    /// M10.5p Stage 3 — fetch new [`FilteredPeakChunk`]s captured
    /// since `start_idx`, serialised as bytes (6 × `f32` per chunk =
    /// 24 bytes stride). Used by the DJ-landmarks waveform palette
    /// to drive the kick-prominence gate from time-domain LF peak
    /// amplitudes rather than μ-law-compressed FFT magnitudes.
    ///
    /// Wire layout per chunk (LE `f32`, in this order): `lf_min`,
    /// `lf_max`, `mf_min`, `mf_max`, `hf_min`, `hf_max`. In v1
    /// the MF / HF fields are always `0.0`.
    ///
    /// Returns an empty `Vec` for Thru-mode decks, for stopped
    /// engines, or when `start_idx >= filtered_peaks_len()`.
    #[must_use]
    pub fn filtered_peaks_extend(&self, deck_idx: u64, start_idx: u64) -> Vec<u8> {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return Vec::new();
        };
        let Some(source) = peak_source_for(running, deck_idx) else {
            return Vec::new();
        };
        let mut chunks: Vec<FilteredPeakChunk> = Vec::new();
        source.extend_filtered_from(usize_from_u64(start_idx), &mut chunks);
        filtered_peak_chunks_to_bytes(&chunks)
    }
}

impl EngineState {
    fn as_running(&self) -> Option<&RunningState> {
        match self {
            EngineState::Running(running) => Some(running.as_ref()),
            EngineState::Stopped => None,
        }
    }
}

/// Snapshot of a deck's playhead state in wall-clock seconds.
///
/// All fields are zero for an empty / stopped deck (`has_track =
/// false`). Returned by [`DubEngine::position`].
#[derive(Debug, Clone, uniffi::Record)]
pub struct PositionInfo {
    /// Wall-clock seconds elapsed from track start (≥ 0, ≤ duration).
    /// Clamped for safe use in time displays and seek targets that
    /// must stay inside the track. Renderers that want to draw the
    /// playhead in a lead-in / lead-out empty-groove region should
    /// read [`Self::playhead_secs_unclamped`] instead.
    pub elapsed_secs: f64,
    /// M10.5t. Raw playhead position in seconds, NOT clamped to
    /// `[0, duration_secs]`. Goes negative when the user has
    /// scratched the deck backwards past the start of the file,
    /// and exceeds `duration_secs` when scratching past the end.
    /// The audio thread is already happy to render silence outside
    /// the track's frame range ([`Deck::read_stereo_at`] returns
    /// `(0, 0)` there); this field lets the UI mirror that
    /// behaviour visually instead of pinning the playhead bracket
    /// to the nearest edge. Time-display consumers should keep
    /// using `elapsed_secs`.
    pub playhead_secs_unclamped: f64,
    /// Wall-clock seconds remaining until track end (≥ 0).
    pub remaining_secs: f64,
    /// Wall-clock total track duration (= `track.frames /
    /// track.sample_rate`).
    pub duration_secs: f64,
    /// Whether the deck is currently advancing the playhead.
    pub is_playing: bool,
    /// Whether the playhead is past the end of the track. UI uses
    /// this to clear a "now playing" badge.
    pub at_end: bool,
    /// `true` if a File-mode track is loaded on this deck. `false`
    /// for empty decks and Thru-mode-only decks (where the
    /// "position" concept doesn't apply because the timecode
    /// drives the rate).
    pub has_track: bool,
    /// M10.6b. `true` while the deck is in Panic-Play state
    /// (PRD §6.1.2) — i.e. running at a held last-known-velocity
    /// rate, ignoring the attached timecode input until either a
    /// clean LFSR re-lock auto-cancels or the UI sends
    /// `cancel_panic_play`. The Apple shell uses this to render
    /// the deck-header `TC · HOLD` amber-dot source-pill state
    /// (M10.6c) and to un-gate overview click-jump in two-deck
    /// Timecode mode.
    pub is_panic_play: bool,
}

impl PositionInfo {
    const EMPTY: Self = Self {
        elapsed_secs: 0.0,
        playhead_secs_unclamped: 0.0,
        remaining_secs: 0.0,
        duration_secs: 0.0,
        is_playing: false,
        at_end: false,
        has_track: false,
        is_panic_play: false,
    };
}

/// Per-track beat grid: BPM, confidence, and per-beat time stamps
/// in seconds (M10.5p).
///
/// Returned by [`DubEngine::beat_grid`]. Computed off-thread inside
/// [`DubEngine::load_track`] (via [`dub_bpm::analyze_beat_grid`])
/// and cached on the deck's [`PeakSource::File`] entry. Live (Thru)
/// decks return an empty grid for now — M11 / M11.5 will plumb the
/// streaming `BpmTracker` output through here too.
///
/// Consumed by the renderer's beat-tick overlay (M10.5p) to draw a
/// dot at every position in `beats`, with every `beats_per_bar`-th
/// dot rendered brighter (the visual "downbeat"; downbeat *phase*
/// is the first emitted beat — see the v0 limitations note on
/// [`dub_bpm::BeatGrid`]).
///
/// `confidence` mirrors the BPM-estimator confidence; if it's
/// `0.0` the grid is empty and callers should not draw anything.
#[derive(Debug, Clone, uniffi::Record)]
pub struct BeatGrid {
    /// Tempo in beats per minute. Meaningful iff `confidence > 0`.
    pub bpm: f64,
    /// Estimator confidence in `[0.0, 1.0]`. `0.0` ⇒ no beats.
    pub confidence: f32,
    /// Beat positions in seconds from sample 0 of the loaded
    /// track. Empty when `confidence == 0`.
    pub beats: Vec<f64>,
    /// Beats per bar. v0 always reports `4`. Reserved for future
    /// time-signature inference (M11+).
    pub beats_per_bar: u32,
}

impl BeatGrid {
    fn empty() -> Self {
        Self {
            bpm: 0.0,
            confidence: 0.0,
            beats: Vec::new(),
            beats_per_bar: 4,
        }
    }

    // `from_core(g: dub_bpm::BeatGrid) -> Self` was removed alongside
    // the M10.5p Stage 1 disable. Re-add when wiring beat-grid
    // computation back into `load_track`; the conversion is a
    // straight field copy with `beats_per_bar: u32::from(g.beats_per_bar)`.
}

/// Metadata for a File-mode loaded track (M10.5 / M10.5r).
///
/// Returned by [`DubEngine::track_info`]. Title / artist are read
/// from the container's tag block at load time (ID3v2 / MP4 atoms /
/// Vorbis comments / RIFF INFO depending on format). Empty strings
/// mean "no tag of that kind present"; the Apple shell falls back
/// to the file stem in that case.
#[derive(Debug, Clone, uniffi::Record)]
pub struct TrackInfo {
    /// Track title read from container metadata. Empty when the
    /// file is untagged.
    pub title: String,
    /// Track artist read from container metadata. Empty when the
    /// file is untagged.
    pub artist: String,
    /// Total duration in seconds.
    pub duration_secs: f64,
    /// Source sample rate (may differ from engine SR).
    pub sample_rate: u32,
    /// 1 (mono) or 2 (stereo).
    pub channels: u32,
    /// BPM annotation, if BPM analysis has been run on the track.
    /// `None` in M10.5 (M11 / M11.5 will run analysis at load time
    /// or pull from the library).
    pub bpm: Option<f64>,
}

/// Stateless tag snapshot for a file on disk (M10.5r).
///
/// Returned by [`read_track_metadata`]. Lets the Apple shell's
/// library / file-browser show title + artist next to each row
/// without paying the full decode-into-RAM cost a `load_track`
/// requires. Empty strings mean "no tag of that kind present" in
/// the container.
#[derive(Debug, Clone, uniffi::Record)]
pub struct TrackMetadata {
    /// Track title (ID3 `TIT2` / Vorbis `TITLE` / MP4 `©nam` / RIFF
    /// `INAM`). Empty if the container has no title tag.
    pub title: String,
    /// Track artist (ID3 `TPE1` / Vorbis `ARTIST` / MP4 `©ART` /
    /// RIFF `IART`). Falls back to the album-artist tag (`TPE2`)
    /// when only that is present. Empty when neither is present.
    pub artist: String,
    /// Album name. Empty when not tagged. Reserved for the M11
    /// library import — the M10.5r browser doesn't render this
    /// yet, but the field is plumbed through so the library work
    /// doesn't have to bump `FFI_VERSION` again.
    pub album: String,
}

impl TrackMetadata {
    /// `true` when no tag field carries text. The Apple shell uses
    /// this to fall back to the file stem on the file-browser row.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.title.is_empty() && self.artist.is_empty() && self.album.is_empty()
    }

    fn from_io(io: IoTrackMetadata) -> Self {
        Self {
            title: io.title.unwrap_or_default(),
            artist: io.artist.unwrap_or_default(),
            album: io.album.unwrap_or_default(),
        }
    }
}

/// Read tag metadata for a file on disk without decoding samples
/// (M10.5r).
///
/// Used by the Apple shell's file browser to populate per-row
/// title / artist columns. Cheap: opens the file, reads the
/// container's tag block, closes the file. ~1 ms per typical
/// MP3 / FLAC on a warm filesystem.
///
/// Returns `None` when:
///
/// * `path` is unreadable or doesn't exist
/// * the file is in a format symphonia can't probe
/// * the file has no recognised tags at all (otherwise an empty
///   `TrackMetadata` would force callers to add a second `is_empty`
///   check; returning `None` lets the caller treat both cases as
///   "no metadata to render" in a single conditional)
///
/// Off-RT only — opens a file handle, allocates inside symphonia.
/// Never call from the audio thread.
#[uniffi::export]
#[must_use]
pub fn read_track_metadata(path: String) -> Option<TrackMetadata> {
    match read_track_metadata_from_disk(&path) {
        Ok(io) if io.is_empty() => None,
        Ok(io) => Some(TrackMetadata::from_io(io)),
        Err(_) => None,
    }
}

/// Helper: lock the engine-state mutex, recovering from a poisoned
/// lock by extracting the inner data. Poisoning can only happen if
/// a UniFFI-exported method panics mid-mutation; since we forbid
/// panics across the boundary, this branch is theoretical, but we
/// handle it defensively so Swift never sees a panic propagated
/// from a `.unwrap()` on `lock()`.
fn lock_state(state: &Mutex<EngineState>) -> std::sync::MutexGuard<'_, EngineState> {
    state
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner)
}

fn peak_source_for(running: &RunningState, deck_idx: u64) -> Option<&PeakSource> {
    let idx: usize = deck_idx.try_into().ok()?;
    running.peaks.get(idx).and_then(|s| s.as_ref())
}

fn deck_idx_to_usize(deck_idx: u64) -> Result<usize, EngineError> {
    let idx: usize = deck_idx
        .try_into()
        .map_err(|_| EngineError::InvalidDeckIndex(deck_idx))?;
    if idx >= dub_engine::DECK_COUNT {
        return Err(EngineError::InvalidDeckIndex(deck_idx));
    }
    Ok(idx)
}

/// Saturating conversion from u64 (UniFFI-friendly) to usize. On
/// 64-bit targets (the only ones we ship to) this is the identity;
/// the saturate guards against a misbehaving Swift caller passing
/// `UInt64.max` to a `start_idx`. Behaviour in that case is "treat
/// it as already past the end and return empty", which matches what
/// `PeakBuffer::extend_chunks` already does for `start_idx >= len`.
fn usize_from_u64(v: u64) -> usize {
    usize::try_from(v).unwrap_or(usize::MAX)
}

/// Open the input device, build the engine, and attach a Thru
/// source on deck 0 with peaks + band capture. Returns the full
/// [`RunningState`] on success.
///
/// Pulled out of `start_thru` so the `Mutex` guard stays narrow:
/// this function never touches `self.state`, only the audio
/// subsystem.
fn start_thru_inner(
    device_name: &str,
    channels_a: &[u32],
    channels_b: Option<&[u32]>,
) -> Result<RunningState, EngineError> {
    // ----- 1. Build InputOptions ------------------------------------
    // Convert 1-based user-facing channel indices to 0-based
    // CoreAudio channel_map. Validation in `start_thru` /
    // `start_thru_two_deck` ensures we have valid channels.
    //
    // Two-deck mode (`channels_b = Some`): open the AU with 4
    // physical channels and use `output_pairs` to demux into two
    // stereo SPSC consumers — pair 0 = deck A, pair 1 = deck B.
    // This is the same M5.6 two-deck-timecode setup, repurposed
    // for two-deck Thru.
    #[allow(clippy::cast_possible_truncation, clippy::cast_possible_wrap)]
    let mut channel_map: Vec<i32> = channels_a.iter().map(|&c| (c as i32) - 1).collect();
    let mut output_pairs: Option<Vec<(u32, u32)>> = None;
    if let Some(chs_b) = channels_b {
        #[allow(clippy::cast_possible_truncation, clippy::cast_possible_wrap)]
        let b_zero: Vec<i32> = chs_b.iter().map(|&c| (c as i32) - 1).collect();
        channel_map.extend(b_zero);
        // Pair 0 = AU outputs 0+1 (deck A), pair 1 = AU outputs 2+3
        // (deck B). Order is fixed by how we appended above.
        output_pairs = Some(vec![(0, 1), (2, 3)]);
    }
    let input_channels = u32::try_from(channel_map.len()).unwrap_or(2);
    let input_opts = InputOptions {
        device_name: Some(device_name.to_string()),
        channels: input_channels,
        channel_map: Some(channel_map),
        output_pairs,
        ..InputOptions::default()
    };

    // ----- 2. Open input device -------------------------------------
    let mut input = AudioInput::start_with_options(&input_opts)
        .map_err(|e| classify_audio_error(e, device_name))?;
    let input_sr_f32 = input.sample_rate();
    #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
    let input_sr = input_sr_f32 as u32;

    // ----- 3. Take consumers for the configured deck(s) ------------
    let consumer_a = input.take_consumer_pair(0).ok_or_else(|| {
        EngineError::AudioStartFailed("input pair 0 consumer already taken".to_string())
    })?;
    let consumer_b = if channels_b.is_some() {
        Some(input.take_consumer_pair(1).ok_or_else(|| {
            EngineError::AudioStartFailed("input pair 1 consumer already taken".to_string())
        })?)
    } else {
        None
    };

    // ----- 4. Build engine ------------------------------------------
    let (engine, mut handle) = Engine::new_with_handle(input_sr_f32, ENGINE_BLOCK_FRAMES);

    // ----- 5. Open output (internal-mixer routing for M10) ----------
    let output_opts = OutputOptions {
        channels: 2,
        ..OutputOptions::default()
    };
    let output = AudioOutput::start_with_options(engine, &output_opts, INTERNAL_MIXER_ROUTING)
        .map_err(|e| EngineError::AudioStartFailed(format!("starting output: {e}")))?;

    // ----- 6. Attach Thru source(s) + peaks on each deck -----------
    let thru_cfg = ThruInputConfig {
        max_block_frames: THRU_MAX_BLOCK_FRAMES,
        input_sample_rate: input_sr_f32,
    };
    let mut peaks: [Option<PeakSource>; 2] = [None, None];

    let peaks_cfg_a = PeakStreamConfig::at(input_sr);
    let peaks_stream_a = handle
        .attach_thru_source_with_peaks_tracking(0, consumer_a, thru_cfg, peaks_cfg_a)
        .map_err(|e| EngineError::AudioStartFailed(format!("attaching thru on deck 0: {e}")))?;
    peaks[0] = Some(PeakSource::Live {
        stream: peaks_stream_a,
        sample_rate: input_sr,
    });

    if let Some(consumer_b) = consumer_b {
        let peaks_cfg_b = PeakStreamConfig::at(input_sr);
        let peaks_stream_b = handle
            .attach_thru_source_with_peaks_tracking(1, consumer_b, thru_cfg, peaks_cfg_b)
            .map_err(|e| EngineError::AudioStartFailed(format!("attaching thru on deck 1: {e}")))?;
        peaks[1] = Some(PeakSource::Live {
            stream: peaks_stream_b,
            sample_rate: input_sr,
        });
    }

    Ok(RunningState {
        peaks,
        file_tracks: [None, None],
        handle,
        output,
        input: Some(input),
        sample_rate: input_sr,
    })
}

/// Map a `dub_audio::AudioError` to the right [`EngineError`]
/// variant based on its content. The HAL doesn't carry typed error
/// kinds for "device not found" vs other failures, so we
/// substring-match its `Display` output. Brittle but contained — if
/// the HAL ever switches to typed errors, this function is the
/// single place that needs to update.
fn classify_audio_error(err: dub_audio::AudioError, device_name: &str) -> EngineError {
    let msg = err.to_string();
    if msg.contains("no input device") || msg.contains("device not found") {
        EngineError::DeviceNotFound(device_name.to_string())
    } else {
        EngineError::AudioStartFailed(msg)
    }
}

/// Open an output AU only — no input, no Thru. Used by
/// [`DubEngine::start_engine`] for the M10.5 File-mode-only path.
fn start_engine_inner(output_channels: u32) -> Result<RunningState, EngineError> {
    // We don't know the output device's SR ahead of time. The
    // existing `start_thru_inner` flow uses the *input* device's SR
    // as the engine SR; for output-only we follow the same
    // convention but read the *output* device's SR instead. Open
    // the AU first with the engine constructed at the system default
    // SR, then read back the actual rate.
    //
    // Simpler approach: build the engine at a placeholder SR
    // (48 kHz, the macOS factory default for built-in output) and
    // let `AudioOutput::start_with_options` align the device to it.
    // If the device refuses, we surface AudioStartFailed.
    const DEFAULT_OUTPUT_SR: f32 = 48_000.0;
    let (engine, handle) = Engine::new_with_handle(DEFAULT_OUTPUT_SR, ENGINE_BLOCK_FRAMES);

    let output_opts = OutputOptions {
        channels: output_channels,
        ..OutputOptions::default()
    };
    let output = AudioOutput::start_with_options(engine, &output_opts, INTERNAL_MIXER_ROUTING)
        .map_err(|e| EngineError::AudioStartFailed(format!("starting output: {e}")))?;

    #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
    let sample_rate = output.sample_rate() as u32;

    Ok(RunningState {
        peaks: [None, None],
        file_tracks: [None, None],
        handle,
        output,
        input: None,
        sample_rate,
    })
}

/// Translate `dub_engine::CommandError` (audio-thread feedback
/// channel saturated, bad deck index) into the FFI-surface
/// equivalent. Pulled out to keep the per-method bodies tidy.
fn map_command_error(e: dub_engine::CommandError) -> EngineError {
    match e {
        dub_engine::CommandError::ChannelFull => EngineError::CommandChannelFull,
        dub_engine::CommandError::InvalidDeck { idx, .. } => {
            EngineError::InvalidDeckIndex(u64::from(idx))
        }
    }
}

/// Serialise broadband peak chunks to a packed little-endian byte
/// buffer matching `#[repr(C)] PeakChunk` (12 bytes per chunk:
/// three `f32` LE).
///
/// Swift reads this as `Data` and reinterprets via
/// `withUnsafeBytes(_:)` into `[PeakChunk]`. Native-endian works
/// because both ARM64 and x86_64 macOS are little-endian.
fn peak_chunks_to_bytes(chunks: &[PeakChunk]) -> Vec<u8> {
    let mut bytes = Vec::with_capacity(std::mem::size_of_val(chunks));
    for c in chunks {
        bytes.extend_from_slice(&c.min.to_le_bytes());
        bytes.extend_from_slice(&c.max.to_le_bytes());
        bytes.extend_from_slice(&c.rms.to_le_bytes());
    }
    bytes
}

/// Serialise per-band peak chunks to a packed little-endian byte
/// buffer matching `#[repr(C)] BandPeakChunk` (32 bytes per chunk:
/// eight `f32` LE).
fn band_peak_chunks_to_bytes(chunks: &[BandPeakChunk]) -> Vec<u8> {
    let mut bytes = Vec::with_capacity(std::mem::size_of_val(chunks));
    for c in chunks {
        for v in c.rms_per_band {
            bytes.extend_from_slice(&v.to_le_bytes());
        }
    }
    bytes
}

/// Serialise per-hop onset chunks to a packed little-endian byte
/// buffer matching `#[repr(C)] OnsetChunk` (4 bytes per chunk: one
/// `f32` LE flux value).
fn onset_chunks_to_bytes(chunks: &[OnsetChunk]) -> Vec<u8> {
    let mut bytes = Vec::with_capacity(std::mem::size_of_val(chunks));
    for c in chunks {
        bytes.extend_from_slice(&c.flux.to_le_bytes());
    }
    bytes
}

/// Serialise time-domain filtered-peak chunks to a packed little-
/// endian byte buffer matching `#[repr(C)] FilteredPeakChunk` (24
/// bytes per chunk: six `f32` LE values in field-declaration order:
/// `lf_min`, `lf_max`, `mf_min`, `mf_max`, `hf_min`, `hf_max`).
fn filtered_peak_chunks_to_bytes(chunks: &[FilteredPeakChunk]) -> Vec<u8> {
    let mut bytes = Vec::with_capacity(std::mem::size_of_val(chunks));
    for c in chunks {
        bytes.extend_from_slice(&c.lf_min.to_le_bytes());
        bytes.extend_from_slice(&c.lf_max.to_le_bytes());
        bytes.extend_from_slice(&c.mf_min.to_le_bytes());
        bytes.extend_from_slice(&c.mf_max.to_le_bytes());
        bytes.extend_from_slice(&c.hf_min.to_le_bytes());
        bytes.extend_from_slice(&c.hf_max.to_le_bytes());
    }
    bytes
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ffi_version_is_fourteen_after_unclamped_playhead() {
        // Bump tripwire: M10-A 1→2 (DubEngine), M10.1 2→3
        // (sample_rate), M10.2 3→4 (start_thru_two_deck), M10.5 4→5
        // (start_engine, load_track, play, pause, seek, position,
        // track_info, PositionInfo + TrackInfo records),
        // M10.5b 5→6 (peaks_generation),
        // M10.5b polish 6→7 (has_external_audio_interface),
        // M10.6b 7→8 (panic_play / cancel_panic_play +
        // PositionInfo.is_panic_play),
        // M10.5l 8→9 (onset_peaks_len / onset_peaks_extend /
        // onset_peaks_chunk_duration_secs),
        // M10.5p 9→10 (beat_grid + BeatGrid record),
        // M10.5p Stage 3 10→11 (filtered_peaks_len /
        // filtered_peaks_extend / filtered_peaks_chunk_duration_secs
        // + FilteredPeakChunk wire format),
        // M10.5r 11→12 (read_track_metadata + TrackMetadata record;
        // TrackInfo.title / TrackInfo.artist now populated from
        // container tags),
        // M10.5s 12→13 (set_deck_rate — mouse-scratch primitive),
        // M10.5t 13→14 (PositionInfo.playhead_secs_unclamped — UI
        // shell can render lead-in / lead-out empty-groove regions).
        assert_eq!(FFI_VERSION, 14);
    }

    #[test]
    fn peak_generation_starts_at_zero_when_stopped() {
        let engine = DubEngine::new();
        assert_eq!(engine.peaks_generation(0), 0);
        assert_eq!(engine.peaks_generation(1), 0);
        assert_eq!(engine.peaks_generation(99), 0);
    }

    #[test]
    fn load_track_on_stopped_engine_returns_not_running() {
        let engine = DubEngine::new();
        let err = engine
            .load_track(0, "/nonexistent.wav".to_string())
            .unwrap_err();
        assert!(matches!(err, EngineError::EngineNotRunning), "got {err:?}");
    }

    #[test]
    fn play_pause_seek_on_stopped_engine_return_not_running() {
        let engine = DubEngine::new();
        for f in [engine.play(0), engine.pause(0), engine.seek(0, 30.0)] {
            assert!(matches!(f.unwrap_err(), EngineError::EngineNotRunning));
        }
    }

    #[test]
    fn load_track_with_invalid_deck_index_returns_invalid_deck() {
        let engine = DubEngine::new();
        // Stopped engine: EngineNotRunning is checked first only after
        // the deck index validates. We check `deck_idx_to_usize` happens
        // first so a clearly-bad deck idx surfaces as InvalidDeckIndex.
        let err = engine.load_track(99, "/tmp/x.wav".to_string()).unwrap_err();
        assert!(matches!(err, EngineError::InvalidDeckIndex(99)));
    }

    #[test]
    fn position_on_stopped_engine_returns_empty() {
        let engine = DubEngine::new();
        let p = engine.position(0);
        assert_eq!(p.elapsed_secs, 0.0);
        assert_eq!(p.duration_secs, 0.0);
        assert_eq!(p.remaining_secs, 0.0);
        assert!(!p.is_playing);
        assert!(!p.has_track);
    }

    #[test]
    fn track_info_on_stopped_engine_returns_none() {
        let engine = DubEngine::new();
        assert!(engine.track_info(0).is_none());
        assert!(engine.track_info(1).is_none());
    }

    #[test]
    fn start_engine_rejects_zero_one_output_channels() {
        let engine = DubEngine::new();
        let err = engine.start_engine(0).unwrap_err();
        assert!(matches!(err, EngineError::InvalidChannels(_)));
        let err = engine.start_engine(1).unwrap_err();
        assert!(matches!(err, EngineError::InvalidChannels(_)));
    }

    #[test]
    fn sample_rate_is_zero_when_stopped() {
        let engine = DubEngine::new();
        assert_eq!(engine.sample_rate(), 0);
    }

    #[test]
    fn greeting_matches() {
        assert_eq!(greeting(), "Dub engine OK");
    }

    #[test]
    fn engine_version_matches_crate() {
        assert_eq!(engine_version(), dub_engine::VERSION);
    }

    #[test]
    fn fresh_engine_reports_no_peaks() {
        let engine = DubEngine::new();
        // No deck has any chunks; idx out of range also returns 0.
        assert_eq!(engine.peaks_len(0), 0);
        assert_eq!(engine.peaks_len(1), 0);
        assert_eq!(engine.peaks_len(99), 0);
        // Extend on a stopped engine is empty (never panics).
        assert!(engine.peaks_extend(0, 0).is_empty());
        assert!(engine.band_peaks_extend(0, 0).is_empty());
        assert!(engine.onset_peaks_extend(0, 0).is_empty());
        assert!(engine.filtered_peaks_extend(0, 0).is_empty());
        assert_eq!(engine.onset_peaks_len(0), 0);
        assert_eq!(engine.filtered_peaks_len(0), 0);
        #[allow(clippy::float_cmp)]
        {
            assert_eq!(engine.peaks_chunk_duration_secs(0), 0.0);
            assert_eq!(engine.band_peaks_chunk_duration_secs(0), 0.0);
            assert_eq!(engine.onset_peaks_chunk_duration_secs(0), 0.0);
        }
    }

    #[test]
    fn stop_thru_is_idempotent_on_stopped_engine() {
        let engine = DubEngine::new();
        engine.stop_thru();
        engine.stop_thru();
        // Still stopped, still functional.
        assert_eq!(engine.peaks_len(0), 0);
    }

    #[test]
    fn start_thru_two_deck_rejects_invalid_or_overlapping_channels() {
        let engine = DubEngine::new();
        // Wrong arity on deck A.
        let err = engine
            .start_thru_two_deck("MacBook Pro Microphone".to_string(), vec![], vec![3, 4])
            .unwrap_err();
        assert!(matches!(err, EngineError::InvalidChannels(_)));
        // Wrong arity on deck B.
        let err = engine
            .start_thru_two_deck("MacBook Pro Microphone".to_string(), vec![1, 2], vec![3])
            .unwrap_err();
        assert!(matches!(err, EngineError::InvalidChannels(_)));
        // Zero index rejected (1-based).
        let err = engine
            .start_thru_two_deck("MacBook Pro Microphone".to_string(), vec![1, 2], vec![0, 3])
            .unwrap_err();
        assert!(matches!(err, EngineError::InvalidChannels(_)));
        // Overlap between A and B is rejected — picking the same
        // physical channel for both decks would silently route the
        // wrong audio.
        let err = engine
            .start_thru_two_deck("MacBook Pro Microphone".to_string(), vec![1, 2], vec![2, 3])
            .unwrap_err();
        match err {
            EngineError::InvalidChannels(combined) => {
                assert_eq!(combined, vec![1, 2, 2, 3]);
            }
            _ => panic!("expected InvalidChannels"),
        }
    }

    #[test]
    fn start_thru_rejects_invalid_channels() {
        let engine = DubEngine::new();

        // Empty / wrong arity.
        let err = engine
            .start_thru("MacBook Pro Microphone".to_string(), vec![])
            .unwrap_err();
        assert!(matches!(err, EngineError::InvalidChannels(_)));
        let err = engine
            .start_thru("MacBook Pro Microphone".to_string(), vec![1, 2, 3])
            .unwrap_err();
        assert!(matches!(err, EngineError::InvalidChannels(_)));

        // Zero is rejected (we use 1-based indices).
        let err = engine
            .start_thru("MacBook Pro Microphone".to_string(), vec![0, 1])
            .unwrap_err();
        assert!(matches!(err, EngineError::InvalidChannels(_)));
    }

    #[test]
    fn peak_chunks_to_bytes_round_trips_one_chunk() {
        let c = PeakChunk {
            min: -0.5,
            max: 0.75,
            rms: 0.6,
        };
        let bytes = peak_chunks_to_bytes(std::slice::from_ref(&c));
        assert_eq!(bytes.len(), 12);
        assert_eq!(f32::from_le_bytes(bytes[0..4].try_into().unwrap()), c.min);
        assert_eq!(f32::from_le_bytes(bytes[4..8].try_into().unwrap()), c.max);
        assert_eq!(f32::from_le_bytes(bytes[8..12].try_into().unwrap()), c.rms);
    }

    #[test]
    fn band_peak_chunks_to_bytes_round_trips_one_chunk() {
        let c = BandPeakChunk {
            rms_per_band: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8],
        };
        let bytes = band_peak_chunks_to_bytes(std::slice::from_ref(&c));
        assert_eq!(bytes.len(), 32);
        for k in 0..8 {
            let off = k * 4;
            let v = f32::from_le_bytes(bytes[off..off + 4].try_into().unwrap());
            #[allow(clippy::cast_precision_loss)]
            let expected = c.rms_per_band[k];
            assert!((v - expected).abs() < 1e-6);
        }
    }

    #[test]
    fn onset_chunks_to_bytes_round_trips_one_chunk() {
        let c = OnsetChunk { flux: 0.42 };
        let bytes = onset_chunks_to_bytes(std::slice::from_ref(&c));
        assert_eq!(bytes.len(), 4);
        let v = f32::from_le_bytes(bytes[0..4].try_into().unwrap());
        assert!((v - c.flux).abs() < 1e-6);
    }

    #[test]
    fn filtered_peak_chunks_to_bytes_round_trips_one_chunk() {
        let c = FilteredPeakChunk {
            lf_min: -0.42,
            lf_max: 0.84,
            mf_min: -0.1,
            mf_max: 0.2,
            hf_min: -0.05,
            hf_max: 0.07,
        };
        let bytes = filtered_peak_chunks_to_bytes(std::slice::from_ref(&c));
        assert_eq!(bytes.len(), 24);
        let read = |o| f32::from_le_bytes(bytes[o..o + 4].try_into().unwrap());
        assert!((read(0) - c.lf_min).abs() < 1e-6);
        assert!((read(4) - c.lf_max).abs() < 1e-6);
        assert!((read(8) - c.mf_min).abs() < 1e-6);
        assert!((read(12) - c.mf_max).abs() < 1e-6);
        assert!((read(16) - c.hf_min).abs() < 1e-6);
        assert!((read(20) - c.hf_max).abs() < 1e-6);
    }

    #[test]
    fn empty_chunks_serialise_to_empty_bytes() {
        assert!(peak_chunks_to_bytes(&[]).is_empty());
        assert!(band_peak_chunks_to_bytes(&[]).is_empty());
        assert!(onset_chunks_to_bytes(&[]).is_empty());
        assert!(filtered_peak_chunks_to_bytes(&[]).is_empty());
    }
}
