//! FFI bindings for the Apple frontend.
//!
//! The Apple shell (`apple/Dub`) links against this crate via the
//! `DubCore.xcframework` that [`scripts/build-xcframework.sh`] produces.
//! Swift bindings are generated by UniFFI in library mode — there is no
//! hand-written `.udl` file; the `#[uniffi::export]` proc macros on
//! Rust items below are the single source of truth.
//!
//! ## Surface
//!
//! * Two free functions for the M0.5 smoke screen: [`greeting`] and
//!   [`engine_version`]. Used by `SmokeScreenView` in the Apple shell.
//! * [`DubEngine`] (M10-A): a stateful handle the Apple shell holds
//!   for the lifetime of a "Thru session". Exposes
//!   - `list_input_devices` (read-only)
//!   - `start_thru` / `stop_thru` (lifecycle)
//!   - `peaks_extend` / `peaks_len` / `peaks_chunk_duration_secs`
//!     (broadband waveform data)
//!   - `band_peaks_extend` / `band_peaks_len` /
//!     `band_peaks_chunk_duration_secs` (M9.5b-shipped 8-band
//!     loudness data — used by the M10.1 multi-colour shader)
//!
//! ## Stability contract
//!
//! All errors are surfaced via [`EngineError`]; no panics ever cross
//! the FFI boundary (`.cursor/rules/ffi.mdc`). All `peaks_*` methods
//! return defensive zero / empty values when the named deck has no
//! capture stream, so the Swift renderer never panics on a stale
//! `start_idx`.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

use std::sync::{Arc, Mutex};

use dub_audio::{AudioInput, AudioOutput, InputOptions, OutputOptions};
use dub_engine::{Engine, EngineHandle, ThruInputConfig, INTERNAL_MIXER_ROUTING};
use dub_peaks::{BandPeakChunk, PeakChunk, PeakStream, PeakStreamConfig};

// UniFFI scaffolding. Emits the C ABI symbols (component contract,
// metadata symbol, RustBuffer alloc/free) that the generated Swift
// bindings depend on. Must be called exactly once per UniFFI-exporting
// crate.
uniffi::setup_scaffolding!();

/// FFI surface version. Bump when adding or removing exported symbols.
///
/// Not currently exposed via UniFFI — Swift consumers verify ABI
/// compatibility through the bindings file UniFFI generates, which
/// embeds a content-hashed checksum per exported function. This
/// constant is kept as a *Rust-side* tripwire so workspace integration
/// tests can fail loudly if someone bumps the surface without updating
/// the version.
///
/// `3`: M10.1 added [`DubEngine::sample_rate`].
/// `4`: M10.2 added [`DubEngine::start_thru_two_deck`] for deck B
///      wiring.
pub const FFI_VERSION: u32 = 4;

/// Returns a static greeting string. The Apple shell calls this on launch
/// to verify it linked the Rust core successfully.
#[uniffi::export]
pub fn greeting() -> String {
    String::from("Dub engine OK")
}

/// Returns the version of the underlying `dub-engine` crate (the
/// `CARGO_PKG_VERSION` baked in at compile time).
#[uniffi::export]
pub fn engine_version() -> String {
    String::from(dub_engine::VERSION)
}

/// Maximum Thru block size, in frames. Mirrors `dub-cli`'s
/// `THRU_MAX_BLOCK_FRAMES` — CoreAudio variable buffers can reach
/// ~4096 frames per IOProc on certain devices, and `ThruSource`'s
/// debug assertion enforces this ceiling so a bigger callback would
/// panic on attach. Sized 1 KiB above CoreAudio's known worst case so
/// any future driver expansion doesn't tip us over silently.
const THRU_MAX_BLOCK_FRAMES: usize = 5120;

/// Engine block size in frames, used when constructing the audio
/// graph. 256 matches the `dub-cli` default and gives a good balance
/// between latency (5.3 ms at 48 kHz) and scheduling overhead.
const ENGINE_BLOCK_FRAMES: usize = 256;

/// Errors surfaced across the UniFFI boundary.
///
/// `flat_error` because most variants don't carry structured data
/// the Swift side needs to branch on — a string is the most
/// ergonomic interop format. The few variants that *do* carry data
/// (e.g. `DeviceNotFound`) embed it into the `Display` impl.
#[derive(Debug, thiserror::Error, uniffi::Error)]
#[uniffi(flat_error)]
#[allow(missing_docs)]
pub enum EngineError {
    #[error("device not found: {0}")]
    DeviceNotFound(String),

    #[error("invalid channels: {0:?}")]
    InvalidChannels(Vec<u32>),

    #[error("audio start failed: {0}")]
    AudioStartFailed(String),

    #[error("engine is already running; call stop_thru first")]
    AlreadyRunning,

    #[error("engine is not running")]
    NotRunning,

    #[error("invalid deck index {0} (valid: 0..{count})", count = dub_engine::DECK_COUNT)]
    InvalidDeckIndex(u64),
}

/// The Apple-side handle to the Dub audio engine.
///
/// Construct one with `DubEngine::new()` (UniFFI emits Swift's
/// `DubEngine()` for this). Methods are all `&self`-on-`Arc<Self>`,
/// so the same handle can be passed across threads and called from
/// the SwiftUI render loop without further synchronization on the
/// Swift side — the internal `Mutex` serialises mutating methods.
///
/// Lifecycle:
///
/// 1. `let engine = DubEngine()`
/// 2. `engine.listInputDevices()` → present the device picker
/// 3. `engine.startThru(deviceName, channels)` → begin capture
/// 4. Render loop polls `peaksLen` + `peaksExtend` for waveform data
/// 5. `engine.stopThru()` on quit (or rely on Swift dropping the
///    last reference; UniFFI's `Drop` impl invokes `stop_thru`
///    automatically)
#[derive(uniffi::Object)]
pub struct DubEngine {
    state: Mutex<EngineState>,
}

/// Internal state machine for the engine.
///
/// `Stopped` is the freshly-constructed, post-`stop_thru`, and
/// post-failed-`start_thru` state. `Running` carries every handle
/// that needs to outlive the audio thread.
enum EngineState {
    Stopped,
    Running(Box<RunningState>),
}

/// Active audio session. Field order matters for `Drop`:
///
/// 1. `peaks` is dropped first → each `PeakStream` joins its
///    decimator thread cleanly.
/// 2. `handle` is dropped second → the engine's main-thread proxy
///    releases its trash channels.
/// 3. `output` is dropped third → `AudioOutput::drop` stops the
///    CoreAudio output AudioUnit and reclaims the `Engine` it
///    owned.
/// 4. `input` is dropped last → no more samples flow.
struct RunningState {
    peaks: [Option<PeakStream>; 2],
    /// Live engine command channel. Held purely so its `Drop` runs
    /// at the right point in the shutdown sequence — we never call
    /// methods on it after the initial attach.
    #[allow(dead_code)]
    handle: EngineHandle,
    /// Live CoreAudio output AudioUnit. Held for `Drop`; renderer
    /// never touches it.
    #[allow(dead_code)]
    output: AudioOutput,
    /// Live CoreAudio input AudioUnit. Held for `Drop`; renderer
    /// never touches it.
    #[allow(dead_code)]
    input: AudioInput,
    sample_rate: u32,
    samples_per_chunk: u32,
    samples_per_band_chunk: Option<u32>,
}

#[uniffi::export]
impl DubEngine {
    /// Construct a fresh engine handle. The audio system is not
    /// touched yet — `start_thru` does that.
    #[uniffi::constructor]
    #[must_use]
    pub fn new() -> Arc<Self> {
        Arc::new(Self {
            state: Mutex::new(EngineState::Stopped),
        })
    }

    /// Enumerate CoreAudio input devices. Returns just their names;
    /// the Swift picker passes one of these strings back to
    /// [`start_thru`].
    ///
    /// Off-RT; safe to call at any time. Returns an empty list if
    /// CoreAudio enumeration fails for any reason (logged via
    /// `eprintln!`; we don't surface enumeration errors as
    /// `EngineError` because that would force every consumer to
    /// branch on a near-impossible failure).
    #[must_use]
    pub fn list_input_devices(&self) -> Vec<String> {
        match dub_audio::list_input_devices() {
            Ok(devs) => devs.into_iter().map(|d| d.name).collect(),
            Err(e) => {
                eprintln!("dub-ffi: list_input_devices failed: {e}");
                Vec::new()
            }
        }
    }

    /// Begin a Thru session: open the input device by name on the
    /// given 1-based channel pair, start a default-stereo output AU,
    /// and attach a `ThruSource` + `PeakStream` on deck 0.
    ///
    /// `channels` is a pair of 1-based CoreAudio input-channel
    /// indices (e.g. `[3, 4]` for the canonical SL3 timecode pair).
    ///
    /// # Errors
    ///
    /// * [`EngineError::AlreadyRunning`] if the engine is already in
    ///   `Running` state. Call `stop_thru` first.
    /// * [`EngineError::InvalidChannels`] if `channels.len() != 2`
    ///   or any channel index is `0` (the FFI uses 1-based indices
    ///   to stay consistent with the CLI).
    /// * [`EngineError::DeviceNotFound`] if no input device matches
    ///   `device_name`.
    /// * [`EngineError::AudioStartFailed`] for any other CoreAudio
    ///   open / attach failure.
    pub fn start_thru(&self, device_name: String, channels: Vec<u32>) -> Result<(), EngineError> {
        let mut state = lock_state(&self.state);
        if matches!(*state, EngineState::Running(_)) {
            return Err(EngineError::AlreadyRunning);
        }

        if channels.len() != 2 || channels.contains(&0) {
            return Err(EngineError::InvalidChannels(channels));
        }

        let running = start_thru_inner(&device_name, &channels, None)?;
        *state = EngineState::Running(Box::new(running));
        Ok(())
    }

    /// Begin a **two-deck** Thru session: open the input device on
    /// the combined 4-channel set (deck A pair + deck B pair), demux
    /// in the IOProc into two stereo SPSC rings, and attach a
    /// `ThruSource` + `PeakStream` on both deck 0 and deck 1.
    ///
    /// The renderer can then poll `peaks_len(0)` / `peaks_len(1)`
    /// independently and show one waveform per deck.
    ///
    /// `channels_a` and `channels_b` are each 1-based pairs (e.g.
    /// `channels_a = [3, 4]`, `channels_b = [5, 6]` for the canonical
    /// SL3 two-deck layout). Channels must not overlap.
    ///
    /// # Errors
    ///
    /// Same as [`start_thru`] for the deck A pair, plus:
    /// * [`EngineError::InvalidChannels`] if `channels_b.len() != 2`,
    ///   any index is `0`, or the A/B pairs share a channel.
    pub fn start_thru_two_deck(
        &self,
        device_name: String,
        channels_a: Vec<u32>,
        channels_b: Vec<u32>,
    ) -> Result<(), EngineError> {
        let mut state = lock_state(&self.state);
        if matches!(*state, EngineState::Running(_)) {
            return Err(EngineError::AlreadyRunning);
        }

        if channels_a.len() != 2 || channels_a.contains(&0) {
            return Err(EngineError::InvalidChannels(channels_a));
        }
        if channels_b.len() != 2 || channels_b.contains(&0) {
            return Err(EngineError::InvalidChannels(channels_b));
        }
        // No channel may appear in both pairs.
        if channels_a.iter().any(|c| channels_b.contains(c)) {
            let mut combined = channels_a;
            combined.extend(channels_b);
            return Err(EngineError::InvalidChannels(combined));
        }

        let running = start_thru_inner(&device_name, &channels_a, Some(&channels_b))?;
        *state = EngineState::Running(Box::new(running));
        Ok(())
    }

    /// Tear down the Thru session. Idempotent — calling `stop_thru`
    /// on an already-stopped engine is a no-op (no error).
    pub fn stop_thru(&self) {
        let mut state = lock_state(&self.state);
        // Move out the running state so its drop order runs while
        // the mutex is held. Dropping the inner state runs the
        // shutdown sequence documented on `RunningState`.
        let prev = std::mem::replace(&mut *state, EngineState::Stopped);
        drop(prev);
    }

    /// Number of broadband [`PeakChunk`]s captured so far on `deck_idx`.
    ///
    /// Returns `0` if the engine is stopped or the deck has no
    /// peaks stream. Cheap (lock-free `AtomicUsize` load after the
    /// state mutex acquire).
    #[must_use]
    pub fn peaks_len(&self, deck_idx: u64) -> u64 {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return 0;
        };
        let Some(stream) = peaks_stream_for(running, deck_idx) else {
            return 0;
        };
        stream.len() as u64
    }

    /// Wall-clock duration of one [`PeakChunk`] on `deck_idx`, in
    /// seconds. `samples_per_chunk / sample_rate`. Returns `0.0`
    /// when stopped / unknown deck — Swift uses the result as a
    /// time-axis scale factor, and a zero scale produces a sane
    /// empty waveform rather than NaN.
    #[must_use]
    pub fn peaks_chunk_duration_secs(&self, deck_idx: u64) -> f64 {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return 0.0;
        };
        if peaks_stream_for(running, deck_idx).is_none() {
            return 0.0;
        }
        f64::from(running.samples_per_chunk) / f64::from(running.sample_rate)
    }

    /// Fetch new [`PeakChunk`]s captured since `start_idx`,
    /// serialised as a raw byte buffer suitable for direct upload
    /// to a `MTLBuffer`. The Swift side reinterprets each 12-byte
    /// stride as a `(f32 min, f32 max, f32 rms)` triple.
    ///
    /// Caller cache-discipline: after each call, Swift advances
    /// its `start_idx` by `bytes.count / 12`. `peaks_len` is the
    /// authoritative total; this method's return covers
    /// `[start_idx, peaks_len)`.
    ///
    /// Returns an empty `Vec` when the engine is stopped, the deck
    /// has no peaks stream, or `start_idx >= len()`.
    #[must_use]
    pub fn peaks_extend(&self, deck_idx: u64, start_idx: u64) -> Vec<u8> {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return Vec::new();
        };
        let Some(stream) = peaks_stream_for(running, deck_idx) else {
            return Vec::new();
        };
        let buffer = stream.buffer();
        let mut chunks: Vec<PeakChunk> = Vec::new();
        let _new_end = buffer.extend_chunks(usize_from_u64(start_idx), &mut chunks);
        peak_chunks_to_bytes(&chunks)
    }

    /// Number of [`BandPeakChunk`]s captured so far on `deck_idx`.
    /// Returns `0` if band capture is disabled or the engine is
    /// stopped.
    #[must_use]
    pub fn band_peaks_len(&self, deck_idx: u64) -> u64 {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return 0;
        };
        let Some(stream) = peaks_stream_for(running, deck_idx) else {
            return 0;
        };
        stream.band_len() as u64
    }

    /// Wall-clock duration of one [`BandPeakChunk`] on `deck_idx`,
    /// in seconds. Equals `BAND_SAMPLES_PER_CHUNK / sample_rate`.
    /// Returns `0.0` if band capture is disabled, the engine is
    /// stopped, or the deck has no stream.
    #[must_use]
    pub fn band_peaks_chunk_duration_secs(&self, deck_idx: u64) -> f64 {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return 0.0;
        };
        let Some(spbc) = running.samples_per_band_chunk else {
            return 0.0;
        };
        if peaks_stream_for(running, deck_idx).is_none() {
            return 0.0;
        }
        f64::from(spbc) / f64::from(running.sample_rate)
    }

    /// Current audio sample rate the engine is running at, in Hz.
    /// Returns `0` when the engine is stopped.
    ///
    /// M10.1 renderers use this to derive `samplesPerChunk` from
    /// `peaks_chunk_duration_secs` — `dur × sample_rate` is the
    /// exact integer cadence the GPU shader needs to map between
    /// the broadband and band rings.
    #[must_use]
    pub fn sample_rate(&self) -> u32 {
        let state = lock_state(&self.state);
        state.as_running().map_or(0, |r| r.sample_rate)
    }

    /// Fetch new [`BandPeakChunk`]s captured since `start_idx`,
    /// serialised as bytes (8 × `f32` per chunk = 32 bytes stride).
    /// Used by the M10.1 multi-colour shader.
    ///
    /// Returns an empty `Vec` when band capture is disabled, the
    /// engine is stopped, or `start_idx >= band_len()`.
    #[must_use]
    pub fn band_peaks_extend(&self, deck_idx: u64, start_idx: u64) -> Vec<u8> {
        let state = lock_state(&self.state);
        let Some(running) = state.as_running() else {
            return Vec::new();
        };
        let Some(stream) = peaks_stream_for(running, deck_idx) else {
            return Vec::new();
        };
        let buffer = stream.buffer();
        let mut chunks: Vec<BandPeakChunk> = Vec::new();
        let _new_end = buffer.extend_band_chunks(usize_from_u64(start_idx), &mut chunks);
        band_peak_chunks_to_bytes(&chunks)
    }
}

impl EngineState {
    fn as_running(&self) -> Option<&RunningState> {
        match self {
            EngineState::Running(running) => Some(running.as_ref()),
            EngineState::Stopped => None,
        }
    }
}

/// Helper: lock the engine-state mutex, recovering from a poisoned
/// lock by extracting the inner data. Poisoning can only happen if
/// a UniFFI-exported method panics mid-mutation; since we forbid
/// panics across the boundary, this branch is theoretical, but we
/// handle it defensively so Swift never sees a panic propagated
/// from a `.unwrap()` on `lock()`.
fn lock_state(state: &Mutex<EngineState>) -> std::sync::MutexGuard<'_, EngineState> {
    state
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner)
}

fn peaks_stream_for(running: &RunningState, deck_idx: u64) -> Option<&PeakStream> {
    let idx: usize = deck_idx.try_into().ok()?;
    running.peaks.get(idx).and_then(|s| s.as_ref())
}

/// Saturating conversion from u64 (UniFFI-friendly) to usize. On
/// 64-bit targets (the only ones we ship to) this is the identity;
/// the saturate guards against a misbehaving Swift caller passing
/// `UInt64.max` to a `start_idx`. Behaviour in that case is "treat
/// it as already past the end and return empty", which matches what
/// `PeakBuffer::extend_chunks` already does for `start_idx >= len`.
fn usize_from_u64(v: u64) -> usize {
    usize::try_from(v).unwrap_or(usize::MAX)
}

/// Open the input device, build the engine, and attach a Thru
/// source on deck 0 with peaks + band capture. Returns the full
/// [`RunningState`] on success.
///
/// Pulled out of `start_thru` so the `Mutex` guard stays narrow:
/// this function never touches `self.state`, only the audio
/// subsystem.
fn start_thru_inner(
    device_name: &str,
    channels_a: &[u32],
    channels_b: Option<&[u32]>,
) -> Result<RunningState, EngineError> {
    // ----- 1. Build InputOptions ------------------------------------
    // Convert 1-based user-facing channel indices to 0-based
    // CoreAudio channel_map. Validation in `start_thru` /
    // `start_thru_two_deck` ensures we have valid channels.
    //
    // Two-deck mode (`channels_b = Some`): open the AU with 4
    // physical channels and use `output_pairs` to demux into two
    // stereo SPSC consumers — pair 0 = deck A, pair 1 = deck B.
    // This is the same M5.6 two-deck-timecode setup, repurposed
    // for two-deck Thru.
    #[allow(clippy::cast_possible_truncation, clippy::cast_possible_wrap)]
    let mut channel_map: Vec<i32> = channels_a.iter().map(|&c| (c as i32) - 1).collect();
    let mut output_pairs: Option<Vec<(u32, u32)>> = None;
    if let Some(chs_b) = channels_b {
        #[allow(clippy::cast_possible_truncation, clippy::cast_possible_wrap)]
        let b_zero: Vec<i32> = chs_b.iter().map(|&c| (c as i32) - 1).collect();
        channel_map.extend(b_zero);
        // Pair 0 = AU outputs 0+1 (deck A), pair 1 = AU outputs 2+3
        // (deck B). Order is fixed by how we appended above.
        output_pairs = Some(vec![(0, 1), (2, 3)]);
    }
    let input_channels = u32::try_from(channel_map.len()).unwrap_or(2);
    let input_opts = InputOptions {
        device_name: Some(device_name.to_string()),
        channels: input_channels,
        channel_map: Some(channel_map),
        output_pairs,
        ..InputOptions::default()
    };

    // ----- 2. Open input device -------------------------------------
    let mut input = AudioInput::start_with_options(&input_opts)
        .map_err(|e| classify_audio_error(e, device_name))?;
    let input_sr_f32 = input.sample_rate();
    #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
    let input_sr = input_sr_f32 as u32;

    // ----- 3. Take consumers for the configured deck(s) ------------
    let consumer_a = input.take_consumer_pair(0).ok_or_else(|| {
        EngineError::AudioStartFailed("input pair 0 consumer already taken".to_string())
    })?;
    let consumer_b = if channels_b.is_some() {
        Some(input.take_consumer_pair(1).ok_or_else(|| {
            EngineError::AudioStartFailed("input pair 1 consumer already taken".to_string())
        })?)
    } else {
        None
    };

    // ----- 4. Build engine ------------------------------------------
    let (engine, mut handle) = Engine::new_with_handle(input_sr_f32, ENGINE_BLOCK_FRAMES);

    // ----- 5. Open output (internal-mixer routing for M10) ----------
    let output_opts = OutputOptions {
        channels: 2,
        ..OutputOptions::default()
    };
    let output = AudioOutput::start_with_options(engine, &output_opts, INTERNAL_MIXER_ROUTING)
        .map_err(|e| EngineError::AudioStartFailed(format!("starting output: {e}")))?;

    // ----- 6. Attach Thru source(s) + peaks on each deck -----------
    let thru_cfg = ThruInputConfig {
        max_block_frames: THRU_MAX_BLOCK_FRAMES,
        input_sample_rate: input_sr_f32,
    };
    let mut peaks: [Option<PeakStream>; 2] = [None, None];

    let peaks_cfg_a = PeakStreamConfig::at(input_sr);
    let bands_enabled = peaks_cfg_a.bands_enabled;
    let peaks_stream_a = handle
        .attach_thru_source_with_peaks_tracking(0, consumer_a, thru_cfg, peaks_cfg_a)
        .map_err(|e| EngineError::AudioStartFailed(format!("attaching thru on deck 0: {e}")))?;

    let samples_per_chunk = u32::try_from(peaks_stream_a.samples_per_chunk()).unwrap_or(u32::MAX);
    let samples_per_band_chunk = if bands_enabled {
        peaks_stream_a
            .samples_per_band_chunk()
            .map(|n| u32::try_from(n).unwrap_or(u32::MAX))
    } else {
        None
    };
    peaks[0] = Some(peaks_stream_a);

    if let Some(consumer_b) = consumer_b {
        let peaks_cfg_b = PeakStreamConfig::at(input_sr);
        let peaks_stream_b = handle
            .attach_thru_source_with_peaks_tracking(1, consumer_b, thru_cfg, peaks_cfg_b)
            .map_err(|e| EngineError::AudioStartFailed(format!("attaching thru on deck 1: {e}")))?;
        peaks[1] = Some(peaks_stream_b);
    }

    Ok(RunningState {
        peaks,
        handle,
        output,
        input,
        sample_rate: input_sr,
        samples_per_chunk,
        samples_per_band_chunk,
    })
}

/// Map a `dub_audio::AudioError` to the right [`EngineError`]
/// variant based on its content. The HAL doesn't carry typed error
/// kinds for "device not found" vs other failures, so we
/// substring-match its `Display` output. Brittle but contained — if
/// the HAL ever switches to typed errors, this function is the
/// single place that needs to update.
fn classify_audio_error(err: dub_audio::AudioError, device_name: &str) -> EngineError {
    let msg = err.to_string();
    if msg.contains("no input device") || msg.contains("device not found") {
        EngineError::DeviceNotFound(device_name.to_string())
    } else {
        EngineError::AudioStartFailed(msg)
    }
}

/// Serialise broadband peak chunks to a packed little-endian byte
/// buffer matching `#[repr(C)] PeakChunk` (12 bytes per chunk:
/// three `f32` LE).
///
/// Swift reads this as `Data` and reinterprets via
/// `withUnsafeBytes(_:)` into `[PeakChunk]`. Native-endian works
/// because both ARM64 and x86_64 macOS are little-endian.
fn peak_chunks_to_bytes(chunks: &[PeakChunk]) -> Vec<u8> {
    let mut bytes = Vec::with_capacity(std::mem::size_of_val(chunks));
    for c in chunks {
        bytes.extend_from_slice(&c.min.to_le_bytes());
        bytes.extend_from_slice(&c.max.to_le_bytes());
        bytes.extend_from_slice(&c.rms.to_le_bytes());
    }
    bytes
}

/// Serialise per-band peak chunks to a packed little-endian byte
/// buffer matching `#[repr(C)] BandPeakChunk` (32 bytes per chunk:
/// eight `f32` LE).
fn band_peak_chunks_to_bytes(chunks: &[BandPeakChunk]) -> Vec<u8> {
    let mut bytes = Vec::with_capacity(std::mem::size_of_val(chunks));
    for c in chunks {
        for v in c.rms_per_band {
            bytes.extend_from_slice(&v.to_le_bytes());
        }
    }
    bytes
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ffi_version_is_four_after_m102_deck_b() {
        // Bump tripwire: M10-A 1→2 (DubEngine), M10.1 2→3
        // (sample_rate), M10.2 3→4 (start_thru_two_deck).
        assert_eq!(FFI_VERSION, 4);
    }

    #[test]
    fn sample_rate_is_zero_when_stopped() {
        let engine = DubEngine::new();
        assert_eq!(engine.sample_rate(), 0);
    }

    #[test]
    fn greeting_matches() {
        assert_eq!(greeting(), "Dub engine OK");
    }

    #[test]
    fn engine_version_matches_crate() {
        assert_eq!(engine_version(), dub_engine::VERSION);
    }

    #[test]
    fn fresh_engine_reports_no_peaks() {
        let engine = DubEngine::new();
        // No deck has any chunks; idx out of range also returns 0.
        assert_eq!(engine.peaks_len(0), 0);
        assert_eq!(engine.peaks_len(1), 0);
        assert_eq!(engine.peaks_len(99), 0);
        // Extend on a stopped engine is empty (never panics).
        assert!(engine.peaks_extend(0, 0).is_empty());
        assert!(engine.band_peaks_extend(0, 0).is_empty());
        #[allow(clippy::float_cmp)]
        {
            assert_eq!(engine.peaks_chunk_duration_secs(0), 0.0);
            assert_eq!(engine.band_peaks_chunk_duration_secs(0), 0.0);
        }
    }

    #[test]
    fn stop_thru_is_idempotent_on_stopped_engine() {
        let engine = DubEngine::new();
        engine.stop_thru();
        engine.stop_thru();
        // Still stopped, still functional.
        assert_eq!(engine.peaks_len(0), 0);
    }

    #[test]
    fn start_thru_two_deck_rejects_invalid_or_overlapping_channels() {
        let engine = DubEngine::new();
        // Wrong arity on deck A.
        let err = engine
            .start_thru_two_deck("MacBook Pro Microphone".to_string(), vec![], vec![3, 4])
            .unwrap_err();
        assert!(matches!(err, EngineError::InvalidChannels(_)));
        // Wrong arity on deck B.
        let err = engine
            .start_thru_two_deck("MacBook Pro Microphone".to_string(), vec![1, 2], vec![3])
            .unwrap_err();
        assert!(matches!(err, EngineError::InvalidChannels(_)));
        // Zero index rejected (1-based).
        let err = engine
            .start_thru_two_deck("MacBook Pro Microphone".to_string(), vec![1, 2], vec![0, 3])
            .unwrap_err();
        assert!(matches!(err, EngineError::InvalidChannels(_)));
        // Overlap between A and B is rejected — picking the same
        // physical channel for both decks would silently route the
        // wrong audio.
        let err = engine
            .start_thru_two_deck("MacBook Pro Microphone".to_string(), vec![1, 2], vec![2, 3])
            .unwrap_err();
        match err {
            EngineError::InvalidChannels(combined) => {
                assert_eq!(combined, vec![1, 2, 2, 3]);
            }
            _ => panic!("expected InvalidChannels"),
        }
    }

    #[test]
    fn start_thru_rejects_invalid_channels() {
        let engine = DubEngine::new();

        // Empty / wrong arity.
        let err = engine
            .start_thru("MacBook Pro Microphone".to_string(), vec![])
            .unwrap_err();
        assert!(matches!(err, EngineError::InvalidChannels(_)));
        let err = engine
            .start_thru("MacBook Pro Microphone".to_string(), vec![1, 2, 3])
            .unwrap_err();
        assert!(matches!(err, EngineError::InvalidChannels(_)));

        // Zero is rejected (we use 1-based indices).
        let err = engine
            .start_thru("MacBook Pro Microphone".to_string(), vec![0, 1])
            .unwrap_err();
        assert!(matches!(err, EngineError::InvalidChannels(_)));
    }

    #[test]
    fn peak_chunks_to_bytes_round_trips_one_chunk() {
        let c = PeakChunk {
            min: -0.5,
            max: 0.75,
            rms: 0.6,
        };
        let bytes = peak_chunks_to_bytes(std::slice::from_ref(&c));
        assert_eq!(bytes.len(), 12);
        assert_eq!(f32::from_le_bytes(bytes[0..4].try_into().unwrap()), c.min);
        assert_eq!(f32::from_le_bytes(bytes[4..8].try_into().unwrap()), c.max);
        assert_eq!(f32::from_le_bytes(bytes[8..12].try_into().unwrap()), c.rms);
    }

    #[test]
    fn band_peak_chunks_to_bytes_round_trips_one_chunk() {
        let c = BandPeakChunk {
            rms_per_band: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8],
        };
        let bytes = band_peak_chunks_to_bytes(std::slice::from_ref(&c));
        assert_eq!(bytes.len(), 32);
        for k in 0..8 {
            let off = k * 4;
            let v = f32::from_le_bytes(bytes[off..off + 4].try_into().unwrap());
            #[allow(clippy::cast_precision_loss)]
            let expected = c.rms_per_band[k];
            assert!((v - expected).abs() < 1e-6);
        }
    }

    #[test]
    fn empty_chunks_serialise_to_empty_bytes() {
        assert!(peak_chunks_to_bytes(&[]).is_empty());
        assert!(band_peak_chunks_to_bytes(&[]).is_empty());
    }
}
